/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Link multiple existing questions to a bank.

Validates ownership or edit permissions before dynamically mapping a batch
of distinct questions natively into the target bank's domain.

Args:
    request: The FastAPI execution request context.
    bank_id: Primary UUID targeting the active Bank.
    payload: The JSON representation containing target associative array values.
    user_id: Unpacked authenticated UUID from authorization token.
    service: Injected core BankQuestionService layer handling validations.

Returns:
    Standard structured APIResponse marking operations successfully complete natively.

Raises:
    BankAccessDeniedError: User fails permission constraint testing natively.
    BankQuestionAlreadyExistsError: Overlapping target arrays encountered.
 * @summary Add Questions To Bank
 */
export const AddQuestionsToBankApiV1BanksBankIdQuestionsPostParams = zod.object({
  "bank_id": zod.uuid()
})

export const AddQuestionsToBankApiV1BanksBankIdQuestionsPostBody = zod.object({
  "question_ids": zod.array(zod.uuid()).describe('List of target question IDs to assign or strip array')
}).describe('Schema for processing a bulk bank question manipulation target request.\n\nContains a robust list of keys executing against Bank operations explicitly.')

/**
 * Remove multiple linked questions from a bank.

Validates edit permissions before natively severing the structural associative relationship
between the provided array endpoints cleanly from the database layer.

Args:
    request: The FastAPI execution request context.
    bank_id: Primary UUID targeting the active Bank.
    payload: The JSON representation containing targets mapped to unlink.
    user_id: Unpacked authenticated UUID from authorization token.
    service: Injected core BankQuestionService layer handling checks.

Returns:
    Standard structured APIResponse confirming removal statuses accurately.

Raises:
    BankAccessDeniedError: User fails requisite explicit permission bounds checking natively.
    BankQuestionNotFoundError: Encountering subsets of question definitions unmapped locally.
 * @summary Remove Questions From Bank
 */
export const RemoveQuestionsFromBankApiV1BanksBankIdQuestionsDeleteParams = zod.object({
  "bank_id": zod.uuid()
})

export const RemoveQuestionsFromBankApiV1BanksBankIdQuestionsDeleteBody = zod.object({
  "question_ids": zod.array(zod.uuid()).describe('List of target question IDs to assign or strip array')
}).describe('Schema for processing a bulk bank question manipulation target request.\n\nContains a robust list of keys executing against Bank operations explicitly.')

export const removeQuestionsFromBankApiV1BanksBankIdQuestionsDeleteResponseSuccessDefault = true;
export const removeQuestionsFromBankApiV1BanksBankIdQuestionsDeleteResponseStatusDefault = 200;
export const removeQuestionsFromBankApiV1BanksBankIdQuestionsDeleteResponseMessageDefault = `Success`;

export const RemoveQuestionsFromBankApiV1BanksBankIdQuestionsDeleteResponse = zod.object({
  "success": zod.boolean().default(removeQuestionsFromBankApiV1BanksBankIdQuestionsDeleteResponseSuccessDefault),
  "status": zod.number().default(removeQuestionsFromBankApiV1BanksBankIdQuestionsDeleteResponseStatusDefault),
  "message": zod.string().default(removeQuestionsFromBankApiV1BanksBankIdQuestionsDeleteResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Retrieve a summary list of questions associated with a bank.

Validates read capabilities before streaming paginated results explicitly mapping
into native JSON arrays across target bank sets.

Args:
    request: The FastAPI execution context.
    bank_id: Primary UUID targeting the active Bank.
    skip: Standard numerical subset offset slice.
    limit: Max depth returned native rows.
    user_id: Intercepted authorization token mapping mapping.
    service: BankQuestionService orchestrating standard reads.

Returns:
    Standard structured APIResponse injecting nested list item payload models internally.

Raises:
    BankNotFoundError: If target entity ID lacks tracking representations natively.
 * @summary Get Bank Questions
 */
export const GetBankQuestionsApiV1BanksBankIdQuestionsGetParams = zod.object({
  "bank_id": zod.uuid()
})

export const getBankQuestionsApiV1BanksBankIdQuestionsGetQuerySkipDefault = 0;
export const getBankQuestionsApiV1BanksBankIdQuestionsGetQuerySkipMin = 0;

export const getBankQuestionsApiV1BanksBankIdQuestionsGetQueryLimitDefault = 10;
export const getBankQuestionsApiV1BanksBankIdQuestionsGetQueryLimitMax = 100;



export const GetBankQuestionsApiV1BanksBankIdQuestionsGetQueryParams = zod.object({
  "skip": zod.number().min(getBankQuestionsApiV1BanksBankIdQuestionsGetQuerySkipMin).default(getBankQuestionsApiV1BanksBankIdQuestionsGetQuerySkipDefault),
  "limit": zod.number().min(1).max(getBankQuestionsApiV1BanksBankIdQuestionsGetQueryLimitMax).default(getBankQuestionsApiV1BanksBankIdQuestionsGetQueryLimitDefault)
})

export const getBankQuestionsApiV1BanksBankIdQuestionsGetResponseSuccessDefault = true;
export const getBankQuestionsApiV1BanksBankIdQuestionsGetResponseStatusDefault = 200;
export const getBankQuestionsApiV1BanksBankIdQuestionsGetResponseMessageDefault = `Success`;

export const GetBankQuestionsApiV1BanksBankIdQuestionsGetResponse = zod.object({
  "success": zod.boolean().default(getBankQuestionsApiV1BanksBankIdQuestionsGetResponseSuccessDefault),
  "status": zod.number().default(getBankQuestionsApiV1BanksBankIdQuestionsGetResponseStatusDefault),
  "message": zod.string().default(getBankQuestionsApiV1BanksBankIdQuestionsGetResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Copy questions from one bank to another.

Validates edit permissions before cloning the selected or complete source bank
question set into the target bank.

Args:
    request: The FastAPI execution request context.
    source_bank_id: Primary UUID targeting the source Bank.
    payload: Request body containing the target bank and copy options.
    user_id: Unpacked authenticated UUID from authorization token.
    service: Injected BankQuestionService handling cloning behavior.

Returns:
    Standard structured APIResponse confirming the copy operation with counts and
    source/target context.

Raises:
    BankNotFoundError: If the source or target bank does not exist.
    BankAccessDeniedError: If the user cannot read the source or edit the target bank.
    BankQuestionAlreadyExistsError: If questions already exist in the target bank.
    QuestionNotFoundError: If selected questions are missing from the source bank.
 * @summary Copy Questions To Bank
 */
export const CopyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostParams = zod.object({
  "source_bank_id": zod.uuid()
})

export const copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostBodyQuestionIdsOneMin = 0;

export const copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostBodyCopyAllDefault = false;

export const CopyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostBody = zod.object({
  "target_bank_id": zod.uuid().describe('Destination bank ID'),
  "question_ids": zod.union([zod.array(zod.uuid()).min(copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostBodyQuestionIdsOneMin),zod.null()]).optional().describe('Optional list of question IDs to copy from the source bank'),
  "copy_all": zod.boolean().default(copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostBodyCopyAllDefault).describe('Copy all questions from the source bank when true')
}).describe('Schema for copying questions from one bank to another.\n\nCarries the destination bank, the optional set of questions to copy, and a flag\nthat allows copying the full source bank when requested.')

/**
 * Retrieve detailed information of a specific question inside a bank.

Verifies associative relationship targets confirming read-access constraints before
supplying deep structural test evaluations and context logic configurations cleanly.

Args:
    request: FastAPI routing metadata tracker natively mapping explicit values.
    bank_id: Top-level constraint filter binding definitions properly.
    question_id: Lower-level constraint targeted lookup exactly matching relations.
    user_id: Validated owner or permission read constraint targets.
    service: Injected backend Service resolving data models.

Returns:
    Standard structural APIResponse nesting completely populated subset representations explicitly.

Raises:
    QuestionNotFoundError: Underlying question ID natively untracked globally.
    BankQuestionNotFoundError: Associative linking targets evaluating false explicitly.
 * @summary Get Bank Question
 */
export const GetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetParams = zod.object({
  "bank_id": zod.uuid(),
  "question_id": zod.uuid()
})

export const getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetResponseSuccessDefault = true;
export const getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetResponseStatusDefault = 200;
export const getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetResponseMessageDefault = `Success`;

export const GetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetResponse = zod.object({
  "success": zod.boolean().default(getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetResponseSuccessDefault),
  "status": zod.number().default(getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetResponseStatusDefault),
  "message": zod.string().default(getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

