/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  APIResponse,
  APIResponseContestDetailResponse,
  APIResponseListContestSummaryResponse,
  APIResponseListInstructorResponse,
  ContestCreate,
  ContestUpdate,
  ExceptionResponse,
  GetAllContestsApiV1ContestsGetParams,
  GetContestInstructorsApiV1ContestsContestIdInstructorsGetParams,
  GetDeletedContestsApiV1ContestsDeletedGetParams,
  HTTPValidationError,
  InstructorManageRequest
} from '../../model';

import { axiosWithAuth } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new contest.

Args:
    request (Request): Framework context.
    contest (ContestCreate): The contest data to create.
    user_id (UUID): The currently authenticated user ID via Keycloak.
    service (ContestService): Injected domain service handling contest operations.

Returns:
    APIResponse: Standardized response encapsulating creation metadata.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks create permission.
    RequestValidationError: If request payload validation fails.
    ContestAlreadyExistsError: If a contest with the same name already exists.
    InvalidContestError: If contest business validation fails.
    ContestOperationError: If contest creation fails unexpectedly.
 * @summary Create a new contest
 */
export const createContestApiV1ContestsPost = (
    contestCreate: ContestCreate,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/contests/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: contestCreate, signal
    },
      options);
    }



export const getCreateContestApiV1ContestsPostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContestApiV1ContestsPost>>, TError,{data: ContestCreate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof createContestApiV1ContestsPost>>, TError,{data: ContestCreate}, TContext> => {

const mutationKey = ['createContestApiV1ContestsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createContestApiV1ContestsPost>>, {data: ContestCreate}> = (props) => {
          const {data} = props ?? {};

          return  createContestApiV1ContestsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateContestApiV1ContestsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createContestApiV1ContestsPost>>>
    export type CreateContestApiV1ContestsPostMutationBody = ContestCreate
    export type CreateContestApiV1ContestsPostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Create a new contest
 */
export const useCreateContestApiV1ContestsPost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContestApiV1ContestsPost>>, TError,{data: ContestCreate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createContestApiV1ContestsPost>>,
        TError,
        {data: ContestCreate},
        TContext
      > => {
      return useMutation(getCreateContestApiV1ContestsPostMutationOptions(options), queryClient);
    }
    /**
 * Get all active contests accessible to the user.

Args:
    request (Request): Framework context.
    user_id (UUID): Authenticated user ID.
    search (str | None): Optional string to search contest names.
    contest_status (ContestStatus | None): Optional filter for contest status.
    is_public (bool | None): Optional filter for visibility.
    page (int): Page number (starts from 1).
    page_size (int): Number of contests per page.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the list of contests and pagination state.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks read permission.
    RequestValidationError: If query parameter validation fails.
    ContestOperationError: If contest retrieval fails unexpectedly.
 * @summary Get all contests
 */
export const getAllContestsApiV1ContestsGet = (
    params?: GetAllContestsApiV1ContestsGetParams,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseListContestSummaryResponse>(
      {url: `/api/v1/contests/`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetAllContestsApiV1ContestsGetQueryKey = (params?: GetAllContestsApiV1ContestsGetParams,) => {
    return [
    `/api/v1/contests/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllContestsApiV1ContestsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError = ExceptionResponse | HTTPValidationError>(params?: GetAllContestsApiV1ContestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllContestsApiV1ContestsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>> = ({ signal }) => getAllContestsApiV1ContestsGet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllContestsApiV1ContestsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>>
export type GetAllContestsApiV1ContestsGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetAllContestsApiV1ContestsGet<TData = Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params: undefined |  GetAllContestsApiV1ContestsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>,
          TError,
          Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllContestsApiV1ContestsGet<TData = Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetAllContestsApiV1ContestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>,
          TError,
          Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllContestsApiV1ContestsGet<TData = Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetAllContestsApiV1ContestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all contests
 */

export function useGetAllContestsApiV1ContestsGet<TData = Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetAllContestsApiV1ContestsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContestsApiV1ContestsGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllContestsApiV1ContestsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get soft-deleted contests accessible to the user.

Args:
    request (Request): Framework context.
    user_id (UUID): Authenticated user ID.
    search (str | None): Optional string to search contest names.
    contest_status (ContestStatus | None): Optional filter for contest status.
    page (int): Page number (starts from 1).
    page_size (int): Number of contests per page.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the list of soft-deleted contests.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks read permission.
    RequestValidationError: If query parameter validation fails.
    ContestOperationError: If contest retrieval fails unexpectedly.
 * @summary Get soft-deleted contests
 */
export const getDeletedContestsApiV1ContestsDeletedGet = (
    params?: GetDeletedContestsApiV1ContestsDeletedGetParams,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseListContestSummaryResponse>(
      {url: `/api/v1/contests/deleted`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetDeletedContestsApiV1ContestsDeletedGetQueryKey = (params?: GetDeletedContestsApiV1ContestsDeletedGetParams,) => {
    return [
    `/api/v1/contests/deleted`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDeletedContestsApiV1ContestsDeletedGetQueryOptions = <TData = Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(params?: GetDeletedContestsApiV1ContestsDeletedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeletedContestsApiV1ContestsDeletedGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>> = ({ signal }) => getDeletedContestsApiV1ContestsDeletedGet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDeletedContestsApiV1ContestsDeletedGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>>
export type GetDeletedContestsApiV1ContestsDeletedGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetDeletedContestsApiV1ContestsDeletedGet<TData = Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params: undefined |  GetDeletedContestsApiV1ContestsDeletedGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>,
          TError,
          Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeletedContestsApiV1ContestsDeletedGet<TData = Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetDeletedContestsApiV1ContestsDeletedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>,
          TError,
          Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeletedContestsApiV1ContestsDeletedGet<TData = Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetDeletedContestsApiV1ContestsDeletedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get soft-deleted contests
 */

export function useGetDeletedContestsApiV1ContestsDeletedGet<TData = Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetDeletedContestsApiV1ContestsDeletedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedContestsApiV1ContestsDeletedGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDeletedContestsApiV1ContestsDeletedGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get detailed information about a specific contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    service (ContestService): Injected domain service.
    user_id (UUID): Authenticated user ID.

Returns:
    APIResponse: Detailed information block for the contest.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks read permission.
    ContestNotFoundError: If the contest does not exist.
    ContestOperationError: If contest retrieval fails unexpectedly.
 * @summary Get contest by ID
 */
export const getContestApiV1ContestsContestIdGet = (
    contestId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseContestDetailResponse>(
      {url: `/api/v1/contests/${contestId}`, method: 'GET', signal
    },
      options);
    }




export const getGetContestApiV1ContestsContestIdGetQueryKey = (contestId: string,) => {
    return [
    `/api/v1/contests/${contestId}`
    ] as const;
    }


export const getGetContestApiV1ContestsContestIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError = ExceptionResponse | HTTPValidationError>(contestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContestApiV1ContestsContestIdGetQueryKey(contestId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>> = ({ signal }) => getContestApiV1ContestsContestIdGet(contestId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(contestId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContestApiV1ContestsContestIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>>
export type GetContestApiV1ContestsContestIdGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetContestApiV1ContestsContestIdGet<TData = Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 contestId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContestApiV1ContestsContestIdGet<TData = Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 contestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContestApiV1ContestsContestIdGet<TData = Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 contestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contest by ID
 */

export function useGetContestApiV1ContestsContestIdGet<TData = Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 contestId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestApiV1ContestsContestIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContestApiV1ContestsContestIdGetQueryOptions(contestId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update contest details.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    contest_data (ContestUpdate): The fields to update.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the updated contest details.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    RequestValidationError: If request payload validation fails.
    ContestNotFoundError: If the contest does not exist.
    InvalidContestError: If contest business validation fails.
    ContestOperationError: If contest update fails unexpectedly.
 * @summary Update contest
 */
export const updateContestApiV1ContestsContestIdPatch = (
    contestId: string,
    contestUpdate: ContestUpdate,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseContestDetailResponse>(
      {url: `/api/v1/contests/${contestId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: contestUpdate, signal
    },
      options);
    }



export const getUpdateContestApiV1ContestsContestIdPatchMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContestApiV1ContestsContestIdPatch>>, TError,{contestId: string;data: ContestUpdate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof updateContestApiV1ContestsContestIdPatch>>, TError,{contestId: string;data: ContestUpdate}, TContext> => {

const mutationKey = ['updateContestApiV1ContestsContestIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateContestApiV1ContestsContestIdPatch>>, {contestId: string;data: ContestUpdate}> = (props) => {
          const {contestId,data} = props ?? {};

          return  updateContestApiV1ContestsContestIdPatch(contestId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateContestApiV1ContestsContestIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateContestApiV1ContestsContestIdPatch>>>
    export type UpdateContestApiV1ContestsContestIdPatchMutationBody = ContestUpdate
    export type UpdateContestApiV1ContestsContestIdPatchMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Update contest
 */
export const useUpdateContestApiV1ContestsContestIdPatch = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContestApiV1ContestsContestIdPatch>>, TError,{contestId: string;data: ContestUpdate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateContestApiV1ContestsContestIdPatch>>,
        TError,
        {contestId: string;data: ContestUpdate},
        TContext
      > => {
      return useMutation(getUpdateContestApiV1ContestsContestIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Hard delete a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest to delete.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks delete permission.
    ContestNotFoundError: If the contest does not exist.
    ContestOperationError: If contest deletion fails unexpectedly.
 * @summary Delete contest
 */
export const deleteContestApiV1ContestsContestIdDelete = (
    contestId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/contests/${contestId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteContestApiV1ContestsContestIdDeleteMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContestApiV1ContestsContestIdDelete>>, TError,{contestId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContestApiV1ContestsContestIdDelete>>, TError,{contestId: string}, TContext> => {

const mutationKey = ['deleteContestApiV1ContestsContestIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContestApiV1ContestsContestIdDelete>>, {contestId: string}> = (props) => {
          const {contestId} = props ?? {};

          return  deleteContestApiV1ContestsContestIdDelete(contestId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteContestApiV1ContestsContestIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContestApiV1ContestsContestIdDelete>>>

    export type DeleteContestApiV1ContestsContestIdDeleteMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Delete contest
 */
export const useDeleteContestApiV1ContestsContestIdDelete = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContestApiV1ContestsContestIdDelete>>, TError,{contestId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContestApiV1ContestsContestIdDelete>>,
        TError,
        {contestId: string},
        TContext
      > => {
      return useMutation(getDeleteContestApiV1ContestsContestIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Publish a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest to publish.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    ContestNotFoundError: If the contest does not exist.
    InvalidContestError: If contest cannot be published in its current state.
    ContestOperationError: If contest publish fails unexpectedly.
 * @summary Publish contest
 */
export const publishContestApiV1ContestsContestIdPublishPost = (
    contestId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/contests/${contestId}/publish`, method: 'POST', signal
    },
      options);
    }



export const getPublishContestApiV1ContestsContestIdPublishPostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishContestApiV1ContestsContestIdPublishPost>>, TError,{contestId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof publishContestApiV1ContestsContestIdPublishPost>>, TError,{contestId: string}, TContext> => {

const mutationKey = ['publishContestApiV1ContestsContestIdPublishPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishContestApiV1ContestsContestIdPublishPost>>, {contestId: string}> = (props) => {
          const {contestId} = props ?? {};

          return  publishContestApiV1ContestsContestIdPublishPost(contestId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublishContestApiV1ContestsContestIdPublishPostMutationResult = NonNullable<Awaited<ReturnType<typeof publishContestApiV1ContestsContestIdPublishPost>>>

    export type PublishContestApiV1ContestsContestIdPublishPostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Publish contest
 */
export const usePublishContestApiV1ContestsContestIdPublishPost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishContestApiV1ContestsContestIdPublishPost>>, TError,{contestId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishContestApiV1ContestsContestIdPublishPost>>,
        TError,
        {contestId: string},
        TContext
      > => {
      return useMutation(getPublishContestApiV1ContestsContestIdPublishPostMutationOptions(options), queryClient);
    }
    /**
 * Soft delete a contest without physically removing it.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest to soft delete.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks delete permission.
    ContestNotFoundError: If the contest does not exist.
    ContestOperationError: If contest soft deletion fails unexpectedly.
 * @summary Soft delete contest
 */
export const softDeleteContestApiV1ContestsContestIdSoftDeleteDelete = (
    contestId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/contests/${contestId}/soft-delete`, method: 'DELETE', signal
    },
      options);
    }



export const getSoftDeleteContestApiV1ContestsContestIdSoftDeleteDeleteMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof softDeleteContestApiV1ContestsContestIdSoftDeleteDelete>>, TError,{contestId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof softDeleteContestApiV1ContestsContestIdSoftDeleteDelete>>, TError,{contestId: string}, TContext> => {

const mutationKey = ['softDeleteContestApiV1ContestsContestIdSoftDeleteDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof softDeleteContestApiV1ContestsContestIdSoftDeleteDelete>>, {contestId: string}> = (props) => {
          const {contestId} = props ?? {};

          return  softDeleteContestApiV1ContestsContestIdSoftDeleteDelete(contestId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SoftDeleteContestApiV1ContestsContestIdSoftDeleteDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof softDeleteContestApiV1ContestsContestIdSoftDeleteDelete>>>

    export type SoftDeleteContestApiV1ContestsContestIdSoftDeleteDeleteMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Soft delete contest
 */
export const useSoftDeleteContestApiV1ContestsContestIdSoftDeleteDelete = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof softDeleteContestApiV1ContestsContestIdSoftDeleteDelete>>, TError,{contestId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof softDeleteContestApiV1ContestsContestIdSoftDeleteDelete>>,
        TError,
        {contestId: string},
        TContext
      > => {
      return useMutation(getSoftDeleteContestApiV1ContestsContestIdSoftDeleteDeleteMutationOptions(options), queryClient);
    }
    /**
 * Restore a soft-deleted contest.

Returns the contest to an active status.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest to restore.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the restored contest data.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    ContestNotFoundError: If the contest does not exist.
    InvalidContestError: If contest cannot be restored in its current state.
    ContestOperationError: If contest restoration fails unexpectedly.
 * @summary Restore soft-deleted contest
 */
export const restoreContestApiV1ContestsContestIdRestorePost = (
    contestId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseContestDetailResponse>(
      {url: `/api/v1/contests/${contestId}/restore`, method: 'POST', signal
    },
      options);
    }



export const getRestoreContestApiV1ContestsContestIdRestorePostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreContestApiV1ContestsContestIdRestorePost>>, TError,{contestId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof restoreContestApiV1ContestsContestIdRestorePost>>, TError,{contestId: string}, TContext> => {

const mutationKey = ['restoreContestApiV1ContestsContestIdRestorePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreContestApiV1ContestsContestIdRestorePost>>, {contestId: string}> = (props) => {
          const {contestId} = props ?? {};

          return  restoreContestApiV1ContestsContestIdRestorePost(contestId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RestoreContestApiV1ContestsContestIdRestorePostMutationResult = NonNullable<Awaited<ReturnType<typeof restoreContestApiV1ContestsContestIdRestorePost>>>

    export type RestoreContestApiV1ContestsContestIdRestorePostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Restore soft-deleted contest
 */
export const useRestoreContestApiV1ContestsContestIdRestorePost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreContestApiV1ContestsContestIdRestorePost>>, TError,{contestId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreContestApiV1ContestsContestIdRestorePost>>,
        TError,
        {contestId: string},
        TContext
      > => {
      return useMutation(getRestoreContestApiV1ContestsContestIdRestorePostMutationOptions(options), queryClient);
    }
    /**
 * Assign instructors to a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    instructor_request (InstructorManageRequest): Request containing instructor IDs.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    RequestValidationError: If request payload validation fails.
    ContestNotFoundError: If the contest does not exist.
    InstructorNotFoundError: If an instructor ID is invalid.
    InstructorAlreadyAssignedError: If an instructor is already assigned.
    ContestOperationError: If instructor assignment fails unexpectedly.
 * @summary Assign instructors to contest
 */
export const assignInstructorsToContestApiV1ContestsContestIdInstructorsPost = (
    contestId: string,
    instructorManageRequest: InstructorManageRequest,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/contests/${contestId}/instructors`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: instructorManageRequest, signal
    },
      options);
    }



export const getAssignInstructorsToContestApiV1ContestsContestIdInstructorsPostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignInstructorsToContestApiV1ContestsContestIdInstructorsPost>>, TError,{contestId: string;data: InstructorManageRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof assignInstructorsToContestApiV1ContestsContestIdInstructorsPost>>, TError,{contestId: string;data: InstructorManageRequest}, TContext> => {

const mutationKey = ['assignInstructorsToContestApiV1ContestsContestIdInstructorsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignInstructorsToContestApiV1ContestsContestIdInstructorsPost>>, {contestId: string;data: InstructorManageRequest}> = (props) => {
          const {contestId,data} = props ?? {};

          return  assignInstructorsToContestApiV1ContestsContestIdInstructorsPost(contestId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AssignInstructorsToContestApiV1ContestsContestIdInstructorsPostMutationResult = NonNullable<Awaited<ReturnType<typeof assignInstructorsToContestApiV1ContestsContestIdInstructorsPost>>>
    export type AssignInstructorsToContestApiV1ContestsContestIdInstructorsPostMutationBody = InstructorManageRequest
    export type AssignInstructorsToContestApiV1ContestsContestIdInstructorsPostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Assign instructors to contest
 */
export const useAssignInstructorsToContestApiV1ContestsContestIdInstructorsPost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignInstructorsToContestApiV1ContestsContestIdInstructorsPost>>, TError,{contestId: string;data: InstructorManageRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignInstructorsToContestApiV1ContestsContestIdInstructorsPost>>,
        TError,
        {contestId: string;data: InstructorManageRequest},
        TContext
      > => {
      return useMutation(getAssignInstructorsToContestApiV1ContestsContestIdInstructorsPostMutationOptions(options), queryClient);
    }
    /**
 * Remove instructors from a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    instructor_request (InstructorManageRequest): Request containing instructor IDs to remove.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    RequestValidationError: If request payload validation fails.
    ContestNotFoundError: If the contest does not exist.
    InstructorNotAssignedError: If an instructor is not currently assigned.
    ContestOperationError: If instructor removal fails unexpectedly.
 * @summary Remove instructors from contest
 */
export const removeInstructorsFromContestApiV1ContestsContestIdInstructorsDelete = (
    contestId: string,
    instructorManageRequest: InstructorManageRequest,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/contests/${contestId}/instructors`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: instructorManageRequest, signal
    },
      options);
    }



export const getRemoveInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeInstructorsFromContestApiV1ContestsContestIdInstructorsDelete>>, TError,{contestId: string;data: InstructorManageRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof removeInstructorsFromContestApiV1ContestsContestIdInstructorsDelete>>, TError,{contestId: string;data: InstructorManageRequest}, TContext> => {

const mutationKey = ['removeInstructorsFromContestApiV1ContestsContestIdInstructorsDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeInstructorsFromContestApiV1ContestsContestIdInstructorsDelete>>, {contestId: string;data: InstructorManageRequest}> = (props) => {
          const {contestId,data} = props ?? {};

          return  removeInstructorsFromContestApiV1ContestsContestIdInstructorsDelete(contestId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeInstructorsFromContestApiV1ContestsContestIdInstructorsDelete>>>
    export type RemoveInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteMutationBody = InstructorManageRequest
    export type RemoveInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Remove instructors from contest
 */
export const useRemoveInstructorsFromContestApiV1ContestsContestIdInstructorsDelete = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeInstructorsFromContestApiV1ContestsContestIdInstructorsDelete>>, TError,{contestId: string;data: InstructorManageRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeInstructorsFromContestApiV1ContestsContestIdInstructorsDelete>>,
        TError,
        {contestId: string;data: InstructorManageRequest},
        TContext
      > => {
      return useMutation(getRemoveInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteMutationOptions(options), queryClient);
    }
    /**
 * Get paginated list of instructors for a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    page (int): Page number (starts from 1).
    page_size (int): Number of instructors per page.
    service (ContestService): Injected domain service.
    user_id (UUID): Authenticated user ID.

Returns:
    APIResponse: Standardized response with list of instructors and pagination state.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks read permission.
    RequestValidationError: If query parameter validation fails.
    ContestNotFoundError: If the contest does not exist.
    ContestOperationError: If instructor retrieval fails unexpectedly.
 * @summary Get contest instructors
 */
export const getContestInstructorsApiV1ContestsContestIdInstructorsGet = (
    contestId: string,
    params?: GetContestInstructorsApiV1ContestsContestIdInstructorsGetParams,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseListInstructorResponse>(
      {url: `/api/v1/contests/${contestId}/instructors`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetContestInstructorsApiV1ContestsContestIdInstructorsGetQueryKey = (contestId: string,
    params?: GetContestInstructorsApiV1ContestsContestIdInstructorsGetParams,) => {
    return [
    `/api/v1/contests/${contestId}/instructors`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetContestInstructorsApiV1ContestsContestIdInstructorsGetQueryOptions = <TData = Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError = ExceptionResponse | HTTPValidationError>(contestId: string,
    params?: GetContestInstructorsApiV1ContestsContestIdInstructorsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContestInstructorsApiV1ContestsContestIdInstructorsGetQueryKey(contestId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>> = ({ signal }) => getContestInstructorsApiV1ContestsContestIdInstructorsGet(contestId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(contestId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContestInstructorsApiV1ContestsContestIdInstructorsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>>
export type GetContestInstructorsApiV1ContestsContestIdInstructorsGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetContestInstructorsApiV1ContestsContestIdInstructorsGet<TData = Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 contestId: string,
    params: undefined |  GetContestInstructorsApiV1ContestsContestIdInstructorsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>,
          TError,
          Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContestInstructorsApiV1ContestsContestIdInstructorsGet<TData = Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 contestId: string,
    params?: GetContestInstructorsApiV1ContestsContestIdInstructorsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>,
          TError,
          Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContestInstructorsApiV1ContestsContestIdInstructorsGet<TData = Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 contestId: string,
    params?: GetContestInstructorsApiV1ContestsContestIdInstructorsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contest instructors
 */

export function useGetContestInstructorsApiV1ContestsContestIdInstructorsGet<TData = Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 contestId: string,
    params?: GetContestInstructorsApiV1ContestsContestIdInstructorsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContestInstructorsApiV1ContestsContestIdInstructorsGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContestInstructorsApiV1ContestsContestIdInstructorsGetQueryOptions(contestId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




