/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Get Users
 */
export const getUsersApiV1UsersGetResponseSuccessDefault = true;
export const getUsersApiV1UsersGetResponseStatusDefault = 200;
export const getUsersApiV1UsersGetResponseMessageDefault = `Success`;

export const GetUsersApiV1UsersGetResponse = zod.object({
  "success": zod.boolean().default(getUsersApiV1UsersGetResponseSuccessDefault),
  "status": zod.number().default(getUsersApiV1UsersGetResponseStatusDefault),
  "message": zod.string().default(getUsersApiV1UsersGetResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * @summary Create User
 */
export const createUserApiV1UsersPostResponseSuccessDefault = true;
export const createUserApiV1UsersPostResponseStatusDefault = 200;
export const createUserApiV1UsersPostResponseMessageDefault = `Success`;

export const CreateUserApiV1UsersPostResponse = zod.object({
  "success": zod.boolean().default(createUserApiV1UsersPostResponseSuccessDefault),
  "status": zod.number().default(createUserApiV1UsersPostResponseStatusDefault),
  "message": zod.string().default(createUserApiV1UsersPostResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Get current logged-in user details from JWT.
 * @summary Get Me
 */
export const getMeApiV1UsersMeGetResponseRolesDefault = [];
export const getMeApiV1UsersMeGetResponseGroupsDefault = [];

export const GetMeApiV1UsersMeGetResponse = zod.object({
  "email": zod.email(),
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "id": zod.string(),
  "roles": zod.array(zod.string()).default(getMeApiV1UsersMeGetResponseRolesDefault),
  "groups": zod.array(zod.string()).default(getMeApiV1UsersMeGetResponseGroupsDefault)
})

/**
 * Synchronize Keycloak users with the local database.

Only administrators can trigger this operation. This endpoint fetches all users
from Keycloak, retrieves their group assignments, and creates new user records
in the database if they don't already exist.

Args:
    admin_user: Current authenticated admin user
    db: Database session

Returns:
    Response with sync status and number of users synced

Raises:
    PermissionDeniedError: If user is not an admin
    KeycloakSyncError: If sync operation fails
 * @summary Sync Keycloak Users
 */
export const syncKeycloakUsersApiV1UsersSyncKeycloakUsersPostResponseSkippedUsersDefault = [];

export const SyncKeycloakUsersApiV1UsersSyncKeycloakUsersPostResponse = zod.object({
  "status": zod.string(),
  "message": zod.string(),
  "users_synced": zod.number(),
  "skipped_count": zod.number(),
  "skipped_users": zod.array(zod.object({
  "user_id": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "reason": zod.string()
})).default(syncKeycloakUsersApiV1UsersSyncKeycloakUsersPostResponseSkippedUsersDefault),
  "synced_by": zod.record(zod.string(), zod.unknown())
})

