import {
    getGetBankQuestionsApiV1BanksBankIdQuestionsGetQueryKey as bankQuestionsKey,
    useAddQuestionsToBankApiV1BanksBankIdQuestionsPost as useAddQuestionsToBank,
    useCloneQuestionsBetweenBanksApiV1BanksSourceBankIdQuestionsClonePost as useCloneBankQuestions,
    useGetBankQuestionsApiV1BanksBankIdQuestionsGet as useGetBankQuestions,
    useRemoveQuestionsFromBankApiV1BanksBankIdQuestionsDelete as useRemoveQuestionsFromBank,
    useUpdateBankQuestionApiV1BanksBankIdQuestionsQuestionIdPut as useUpdateBankQuestion,
} from "@/api/generated/bank-questions/bank-questions";
import {
    getGetAllBanksApiV1BanksGetQueryKey as allBanksKey,
    getGetBankApiV1BanksBankIdGetQueryKey as bankDetailKey,
    getGetBankSharesApiV1BanksBankIdSharesGetQueryKey as bankSharesKey,
    useDeleteBankApiV1BanksBankIdDelete as useDeleteBank,
    useGetAllBanksApiV1BanksGet as useGetAllBanks,
    useGetBankApiV1BanksBankIdGet as useGetBankDetail,
    useGetBankSharesApiV1BanksBankIdSharesGet as useGetBankShares,
    useShareBankApiV1BanksBankIdSharesPost as useShareBank,
    useSoftDeleteBankApiV1BanksBankIdSoftDeleteDelete as useSoftDeleteBank,
    useUnshareBankApiV1BanksBankIdSharesTargetUserIdDelete as useUnshareBank,
    useUpdateBankApiV1BanksBankIdPatch as useUpdateBank,
    useUpdateBankSharesApiV1BanksBankIdSharesPatch as useUpdateBankShares,
} from "@/api/generated/banks/banks";

export {
    allBanksKey,
    bankDetailKey,
    bankQuestionsKey,
    bankSharesKey,
    useAddQuestionsToBank,
    useCloneBankQuestions,
    useDeleteBank,
    useGetAllBanks,
    useGetBankDetail,
    useGetBankQuestions,
    useGetBankShares,
    useRemoveQuestionsFromBank,
    useShareBank,
    useSoftDeleteBank,
    useUnshareBank,
    useUpdateBank,
    useUpdateBankQuestion,
    useUpdateBankShares,
};
