/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BankQuestionBulk,
  BankQuestionCopyRequest,
  ExceptionResponse,
  GetBankQuestionsApiV1BanksBankIdQuestionsGetParams,
  HTTPValidationError
} from '../../model';

import { axiosWithAuth } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Link multiple existing questions to a bank.

Validates ownership or edit permissions before dynamically mapping a batch
of distinct questions natively into the target bank's domain.

Args:
    request: The FastAPI execution request context.
    bank_id: Primary UUID targeting the active Bank.
    payload: The JSON representation containing target associative array values.
    user_id: Unpacked authenticated UUID from authorization token.
    service: Injected core BankQuestionService layer handling validations.

Returns:
    Standard structured APIResponse marking operations successfully complete natively.

Raises:
    BankAccessDeniedError: User fails permission constraint testing natively.
    BankQuestionAlreadyExistsError: Overlapping target arrays encountered.
 * @summary Add Questions To Bank
 */
export const addQuestionsToBankApiV1BanksBankIdQuestionsPost = (
    bankId: string,
    bankQuestionBulk: BankQuestionBulk,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<unknown>(
      {url: `/api/v1/banks/${bankId}/questions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bankQuestionBulk, signal
    },
      options);
    }



export const getAddQuestionsToBankApiV1BanksBankIdQuestionsPostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addQuestionsToBankApiV1BanksBankIdQuestionsPost>>, TError,{bankId: string;data: BankQuestionBulk}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof addQuestionsToBankApiV1BanksBankIdQuestionsPost>>, TError,{bankId: string;data: BankQuestionBulk}, TContext> => {

const mutationKey = ['addQuestionsToBankApiV1BanksBankIdQuestionsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addQuestionsToBankApiV1BanksBankIdQuestionsPost>>, {bankId: string;data: BankQuestionBulk}> = (props) => {
          const {bankId,data} = props ?? {};

          return  addQuestionsToBankApiV1BanksBankIdQuestionsPost(bankId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddQuestionsToBankApiV1BanksBankIdQuestionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof addQuestionsToBankApiV1BanksBankIdQuestionsPost>>>
    export type AddQuestionsToBankApiV1BanksBankIdQuestionsPostMutationBody = BankQuestionBulk
    export type AddQuestionsToBankApiV1BanksBankIdQuestionsPostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Add Questions To Bank
 */
export const useAddQuestionsToBankApiV1BanksBankIdQuestionsPost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addQuestionsToBankApiV1BanksBankIdQuestionsPost>>, TError,{bankId: string;data: BankQuestionBulk}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addQuestionsToBankApiV1BanksBankIdQuestionsPost>>,
        TError,
        {bankId: string;data: BankQuestionBulk},
        TContext
      > => {
      return useMutation(getAddQuestionsToBankApiV1BanksBankIdQuestionsPostMutationOptions(options), queryClient);
    }
    /**
 * Remove multiple linked questions from a bank.

Validates edit permissions before natively severing the structural associative relationship
between the provided array endpoints cleanly from the database layer.

Args:
    request: The FastAPI execution request context.
    bank_id: Primary UUID targeting the active Bank.
    payload: The JSON representation containing targets mapped to unlink.
    user_id: Unpacked authenticated UUID from authorization token.
    service: Injected core BankQuestionService layer handling checks.

Returns:
    Standard structured APIResponse confirming removal statuses accurately.

Raises:
    BankAccessDeniedError: User fails requisite explicit permission bounds checking natively.
    BankQuestionNotFoundError: Encountering subsets of question definitions unmapped locally.
 * @summary Remove Questions From Bank
 */
export const removeQuestionsFromBankApiV1BanksBankIdQuestionsDelete = (
    bankId: string,
    bankQuestionBulk: BankQuestionBulk,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<unknown>(
      {url: `/api/v1/banks/${bankId}/questions`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: bankQuestionBulk, signal
    },
      options);
    }



export const getRemoveQuestionsFromBankApiV1BanksBankIdQuestionsDeleteMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeQuestionsFromBankApiV1BanksBankIdQuestionsDelete>>, TError,{bankId: string;data: BankQuestionBulk}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof removeQuestionsFromBankApiV1BanksBankIdQuestionsDelete>>, TError,{bankId: string;data: BankQuestionBulk}, TContext> => {

const mutationKey = ['removeQuestionsFromBankApiV1BanksBankIdQuestionsDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeQuestionsFromBankApiV1BanksBankIdQuestionsDelete>>, {bankId: string;data: BankQuestionBulk}> = (props) => {
          const {bankId,data} = props ?? {};

          return  removeQuestionsFromBankApiV1BanksBankIdQuestionsDelete(bankId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveQuestionsFromBankApiV1BanksBankIdQuestionsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeQuestionsFromBankApiV1BanksBankIdQuestionsDelete>>>
    export type RemoveQuestionsFromBankApiV1BanksBankIdQuestionsDeleteMutationBody = BankQuestionBulk
    export type RemoveQuestionsFromBankApiV1BanksBankIdQuestionsDeleteMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Remove Questions From Bank
 */
export const useRemoveQuestionsFromBankApiV1BanksBankIdQuestionsDelete = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeQuestionsFromBankApiV1BanksBankIdQuestionsDelete>>, TError,{bankId: string;data: BankQuestionBulk}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeQuestionsFromBankApiV1BanksBankIdQuestionsDelete>>,
        TError,
        {bankId: string;data: BankQuestionBulk},
        TContext
      > => {
      return useMutation(getRemoveQuestionsFromBankApiV1BanksBankIdQuestionsDeleteMutationOptions(options), queryClient);
    }
    /**
 * Retrieve a summary list of questions associated with a bank.

Validates read capabilities before streaming paginated results explicitly mapping
into native JSON arrays across target bank sets.

Args:
    request: The FastAPI execution context.
    bank_id: Primary UUID targeting the active Bank.
    skip: Standard numerical subset offset slice.
    limit: Max depth returned native rows.
    user_id: Intercepted authorization token mapping mapping.
    service: BankQuestionService orchestrating standard reads.

Returns:
    Standard structured APIResponse injecting nested list item payload models internally.

Raises:
    BankNotFoundError: If target entity ID lacks tracking representations natively.
 * @summary Get Bank Questions
 */
export const getBankQuestionsApiV1BanksBankIdQuestionsGet = (
    bankId: string,
    params?: GetBankQuestionsApiV1BanksBankIdQuestionsGetParams,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<unknown>(
      {url: `/api/v1/banks/${bankId}/questions`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetBankQuestionsApiV1BanksBankIdQuestionsGetQueryKey = (bankId: string,
    params?: GetBankQuestionsApiV1BanksBankIdQuestionsGetParams,) => {
    return [
    `/api/v1/banks/${bankId}/questions`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetBankQuestionsApiV1BanksBankIdQuestionsGetQueryOptions = <TData = Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError = ExceptionResponse | HTTPValidationError>(bankId: string,
    params?: GetBankQuestionsApiV1BanksBankIdQuestionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBankQuestionsApiV1BanksBankIdQuestionsGetQueryKey(bankId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>> = ({ signal }) => getBankQuestionsApiV1BanksBankIdQuestionsGet(bankId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(bankId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBankQuestionsApiV1BanksBankIdQuestionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>>
export type GetBankQuestionsApiV1BanksBankIdQuestionsGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetBankQuestionsApiV1BanksBankIdQuestionsGet<TData = Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string,
    params: undefined |  GetBankQuestionsApiV1BanksBankIdQuestionsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>,
          TError,
          Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBankQuestionsApiV1BanksBankIdQuestionsGet<TData = Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string,
    params?: GetBankQuestionsApiV1BanksBankIdQuestionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>,
          TError,
          Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBankQuestionsApiV1BanksBankIdQuestionsGet<TData = Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string,
    params?: GetBankQuestionsApiV1BanksBankIdQuestionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Bank Questions
 */

export function useGetBankQuestionsApiV1BanksBankIdQuestionsGet<TData = Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string,
    params?: GetBankQuestionsApiV1BanksBankIdQuestionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionsApiV1BanksBankIdQuestionsGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBankQuestionsApiV1BanksBankIdQuestionsGetQueryOptions(bankId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Copy questions from one bank to another.

Validates edit permissions before cloning the selected or complete source bank
question set into the target bank.

Args:
    request: The FastAPI execution request context.
    source_bank_id: Primary UUID targeting the source Bank.
    payload: Request body containing the target bank and copy options.
    user_id: Unpacked authenticated UUID from authorization token.
    service: Injected BankQuestionService handling cloning behavior.

Returns:
    Standard structured APIResponse confirming the copy operation with counts and
    source/target context.

Raises:
    BankNotFoundError: If the source or target bank does not exist.
    BankAccessDeniedError: If the user cannot read the source or edit the target bank.
    BankQuestionAlreadyExistsError: If questions already exist in the target bank.
    QuestionNotFoundError: If selected questions are missing from the source bank.
 * @summary Copy Questions To Bank
 */
export const copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost = (
    sourceBankId: string,
    bankQuestionCopyRequest: BankQuestionCopyRequest,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<unknown>(
      {url: `/api/v1/banks/${sourceBankId}/questions/copy`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bankQuestionCopyRequest, signal
    },
      options);
    }



export const getCopyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost>>, TError,{sourceBankId: string;data: BankQuestionCopyRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost>>, TError,{sourceBankId: string;data: BankQuestionCopyRequest}, TContext> => {

const mutationKey = ['copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost>>, {sourceBankId: string;data: BankQuestionCopyRequest}> = (props) => {
          const {sourceBankId,data} = props ?? {};

          return  copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost(sourceBankId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CopyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostMutationResult = NonNullable<Awaited<ReturnType<typeof copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost>>>
    export type CopyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostMutationBody = BankQuestionCopyRequest
    export type CopyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Copy Questions To Bank
 */
export const useCopyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost>>, TError,{sourceBankId: string;data: BankQuestionCopyRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof copyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPost>>,
        TError,
        {sourceBankId: string;data: BankQuestionCopyRequest},
        TContext
      > => {
      return useMutation(getCopyQuestionsToBankApiV1BanksSourceBankIdQuestionsCopyPostMutationOptions(options), queryClient);
    }
    /**
 * Retrieve detailed information of a specific question inside a bank.

Verifies associative relationship targets confirming read-access constraints before
supplying deep structural test evaluations and context logic configurations cleanly.

Args:
    request: FastAPI routing metadata tracker natively mapping explicit values.
    bank_id: Top-level constraint filter binding definitions properly.
    question_id: Lower-level constraint targeted lookup exactly matching relations.
    user_id: Validated owner or permission read constraint targets.
    service: Injected backend Service resolving data models.

Returns:
    Standard structural APIResponse nesting completely populated subset representations explicitly.

Raises:
    QuestionNotFoundError: Underlying question ID natively untracked globally.
    BankQuestionNotFoundError: Associative linking targets evaluating false explicitly.
 * @summary Get Bank Question
 */
export const getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet = (
    bankId: string,
    questionId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<unknown>(
      {url: `/api/v1/banks/${bankId}/questions/${questionId}`, method: 'GET', signal
    },
      options);
    }




export const getGetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetQueryKey = (bankId: string,
    questionId: string,) => {
    return [
    `/api/v1/banks/${bankId}/questions/${questionId}`
    ] as const;
    }


export const getGetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(bankId: string,
    questionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetQueryKey(bankId,questionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>> = ({ signal }) => getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet(bankId,questionId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(bankId && questionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>>
export type GetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet<TData = Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string,
    questionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>,
          TError,
          Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet<TData = Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string,
    questionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>,
          TError,
          Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet<TData = Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string,
    questionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Bank Question
 */

export function useGetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet<TData = Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string,
    questionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankQuestionApiV1BanksBankIdQuestionsQuestionIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBankQuestionApiV1BanksBankIdQuestionsQuestionIdGetQueryOptions(bankId,questionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




