/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExceptionResponse,
  HTTPValidationError,
  QuestionCreate,
  QuestionResponse,
  QuestionUpdate
} from '../../model';

import { axiosWithAuth } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new question.

Args:
    request: FastAPI request object
    data: QuestionCreate Pydantic model
    current_user: Dictionary holding keycloak JWT claims
    db: Injected database session
    service: Injected QuestionService

Returns:
    QuestionResponse: The created question details

Raises:
    InvalidQuestionError: When validation logic fails
 * @summary Create Question
 */
export const createQuestionApiV1QuestionsPost = (
    questionCreate: QuestionCreate,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<QuestionResponse>(
      {url: `/api/v1/questions/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: questionCreate, signal
    },
      options);
    }



export const getCreateQuestionApiV1QuestionsPostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createQuestionApiV1QuestionsPost>>, TError,{data: QuestionCreate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof createQuestionApiV1QuestionsPost>>, TError,{data: QuestionCreate}, TContext> => {

const mutationKey = ['createQuestionApiV1QuestionsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createQuestionApiV1QuestionsPost>>, {data: QuestionCreate}> = (props) => {
          const {data} = props ?? {};

          return  createQuestionApiV1QuestionsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateQuestionApiV1QuestionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createQuestionApiV1QuestionsPost>>>
    export type CreateQuestionApiV1QuestionsPostMutationBody = QuestionCreate
    export type CreateQuestionApiV1QuestionsPostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Create Question
 */
export const useCreateQuestionApiV1QuestionsPost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createQuestionApiV1QuestionsPost>>, TError,{data: QuestionCreate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createQuestionApiV1QuestionsPost>>,
        TError,
        {data: QuestionCreate},
        TContext
      > => {
      return useMutation(getCreateQuestionApiV1QuestionsPostMutationOptions(options), queryClient);
    }
    /**
 * Retrieve a question by ID.

Args:
    request: FastAPI request object
    question_id: ID of the question
    current_user: Dictionary holding keycloak JWT claims
    db: Injected database session
    service: Injected QuestionService

Returns:
    QuestionResponse: The queried question details

Raises:
    QuestionNotFoundError: If the question does not exist
    QuestionPermissionError: If user lacks permission
 * @summary Get Question
 */
export const getQuestionApiV1QuestionsQuestionIdGet = (
    questionId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<QuestionResponse>(
      {url: `/api/v1/questions/${questionId}`, method: 'GET', signal
    },
      options);
    }




export const getGetQuestionApiV1QuestionsQuestionIdGetQueryKey = (questionId: string,) => {
    return [
    `/api/v1/questions/${questionId}`
    ] as const;
    }


export const getGetQuestionApiV1QuestionsQuestionIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(questionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestionApiV1QuestionsQuestionIdGetQueryKey(questionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>> = ({ signal }) => getQuestionApiV1QuestionsQuestionIdGet(questionId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(questionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionApiV1QuestionsQuestionIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>>
export type GetQuestionApiV1QuestionsQuestionIdGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetQuestionApiV1QuestionsQuestionIdGet<TData = Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 questionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>,
          TError,
          Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionApiV1QuestionsQuestionIdGet<TData = Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 questionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>,
          TError,
          Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionApiV1QuestionsQuestionIdGet<TData = Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 questionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Question
 */

export function useGetQuestionApiV1QuestionsQuestionIdGet<TData = Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 questionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionApiV1QuestionsQuestionIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestionApiV1QuestionsQuestionIdGetQueryOptions(questionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update a question.

Args:
    request: FastAPI request object
    question_id: ID of the question
    data: QuestionUpdate Pydantic model
    current_user: Dictionary holding keycloak JWT claims
    db: Injected database session
    service: Injected QuestionService

Returns:
    QuestionResponse: The updated question details

Raises:
    QuestionNotFoundError: If the question does not exist
    InvalidQuestionError: When validation logic fails
    QuestionPermissionError: If user lacks management permissions
 * @summary Update Question
 */
export const updateQuestionApiV1QuestionsQuestionIdPatch = (
    questionId: string,
    questionUpdate: QuestionUpdate,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<QuestionResponse>(
      {url: `/api/v1/questions/${questionId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: questionUpdate, signal
    },
      options);
    }



export const getUpdateQuestionApiV1QuestionsQuestionIdPatchMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQuestionApiV1QuestionsQuestionIdPatch>>, TError,{questionId: string;data: QuestionUpdate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof updateQuestionApiV1QuestionsQuestionIdPatch>>, TError,{questionId: string;data: QuestionUpdate}, TContext> => {

const mutationKey = ['updateQuestionApiV1QuestionsQuestionIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateQuestionApiV1QuestionsQuestionIdPatch>>, {questionId: string;data: QuestionUpdate}> = (props) => {
          const {questionId,data} = props ?? {};

          return  updateQuestionApiV1QuestionsQuestionIdPatch(questionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateQuestionApiV1QuestionsQuestionIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateQuestionApiV1QuestionsQuestionIdPatch>>>
    export type UpdateQuestionApiV1QuestionsQuestionIdPatchMutationBody = QuestionUpdate
    export type UpdateQuestionApiV1QuestionsQuestionIdPatchMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Update Question
 */
export const useUpdateQuestionApiV1QuestionsQuestionIdPatch = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQuestionApiV1QuestionsQuestionIdPatch>>, TError,{questionId: string;data: QuestionUpdate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateQuestionApiV1QuestionsQuestionIdPatch>>,
        TError,
        {questionId: string;data: QuestionUpdate},
        TContext
      > => {
      return useMutation(getUpdateQuestionApiV1QuestionsQuestionIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete a question by ID.

Args:
    request: FastAPI request object
    question_id: ID of the question
    current_user: Dictionary holding keycloak JWT claims
    db: Injected database session
    service: Injected QuestionService

Raises:
    QuestionNotFoundError: If the question does not exist
    QuestionPermissionError: If user lacks management permissions
 * @summary Delete Question
 */
export const deleteQuestionApiV1QuestionsQuestionIdDelete = (
    questionId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<void>(
      {url: `/api/v1/questions/${questionId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteQuestionApiV1QuestionsQuestionIdDeleteMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQuestionApiV1QuestionsQuestionIdDelete>>, TError,{questionId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteQuestionApiV1QuestionsQuestionIdDelete>>, TError,{questionId: string}, TContext> => {

const mutationKey = ['deleteQuestionApiV1QuestionsQuestionIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteQuestionApiV1QuestionsQuestionIdDelete>>, {questionId: string}> = (props) => {
          const {questionId} = props ?? {};

          return  deleteQuestionApiV1QuestionsQuestionIdDelete(questionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteQuestionApiV1QuestionsQuestionIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQuestionApiV1QuestionsQuestionIdDelete>>>

    export type DeleteQuestionApiV1QuestionsQuestionIdDeleteMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Delete Question
 */
export const useDeleteQuestionApiV1QuestionsQuestionIdDelete = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQuestionApiV1QuestionsQuestionIdDelete>>, TError,{questionId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteQuestionApiV1QuestionsQuestionIdDelete>>,
        TError,
        {questionId: string},
        TContext
      > => {
      return useMutation(getDeleteQuestionApiV1QuestionsQuestionIdDeleteMutationOptions(options), queryClient);
    }
