/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Execute a system health check monitored against active database connections natively.
 * @summary Health Check
 */
export const healthCheckApiHealthGetResponseSuccessDefault = true;
export const healthCheckApiHealthGetResponseStatusDefault = 200;
export const healthCheckApiHealthGetResponseMessageDefault = `Success`;

export const HealthCheckApiHealthGetResponse = zod.object({
  "success": zod.boolean().default(healthCheckApiHealthGetResponseSuccessDefault),
  "status": zod.number().default(healthCheckApiHealthGetResponseStatusDefault),
  "message": zod.string().default(healthCheckApiHealthGetResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

