/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Execute a system health check monitored against active database connections natively.
 * @summary Health Check
 */
export const HealthCheckApiHealthGetResponse = zod.unknown()

