/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Create a new question.

Args:
    request: FastAPI request object
    data: QuestionCreate Pydantic model
    current_user: Dictionary holding keycloak JWT claims
    db: Injected database session
    service: Injected QuestionService

Returns:
    QuestionResponse: The created question details

Raises:
    InvalidQuestionError: When validation logic fails
 * @summary Create Question
 */
export const createQuestionApiV1QuestionsPostBodyTimeLimitMsExclusiveMin = 0;

export const createQuestionApiV1QuestionsPostBodyMemoryLimitMbExclusiveMin = 0;



export const CreateQuestionApiV1QuestionsPostBody = zod.object({
  "question_text": zod.string().describe('The problem statement and description'),
  "difficulty": zod.enum(['EASY', 'MEDIUM', 'HARD']).describe('Difficulty level of the question'),
  "allowed_languages": zod.array(zod.string()).describe('List of allowed programming languages'),
  "testcases": zod.array(zod.record(zod.string(), zod.unknown())).describe('List of testcases with input\/output and visibility'),
  "time_limit_ms": zod.number().gt(createQuestionApiV1QuestionsPostBodyTimeLimitMsExclusiveMin).describe('Time limit in milliseconds'),
  "memory_limit_mb": zod.number().gt(createQuestionApiV1QuestionsPostBodyMemoryLimitMbExclusiveMin).describe('Memory limit in megabytes')
})

/**
 * Retrieve a question by ID.

Args:
    request: FastAPI request object
    question_id: ID of the question
    current_user: Dictionary holding keycloak JWT claims
    db: Injected database session
    service: Injected QuestionService

Returns:
    QuestionResponse: The queried question details

Raises:
    QuestionNotFoundError: If the question does not exist
    QuestionPermissionError: If user lacks permission
 * @summary Get Question
 */
export const GetQuestionApiV1QuestionsQuestionIdGetParams = zod.object({
  "question_id": zod.uuid()
})

export const GetQuestionApiV1QuestionsQuestionIdGetResponse = zod.unknown()

/**
 * Update a question.

Args:
    request: FastAPI request object
    question_id: ID of the question
    data: QuestionUpdate Pydantic model
    current_user: Dictionary holding keycloak JWT claims
    db: Injected database session
    service: Injected QuestionService

Returns:
    QuestionResponse: The updated question details

Raises:
    QuestionNotFoundError: If the question does not exist
    InvalidQuestionError: When validation logic fails
    QuestionPermissionError: If user lacks management permissions
 * @summary Update Question
 */
export const UpdateQuestionApiV1QuestionsQuestionIdPatchParams = zod.object({
  "question_id": zod.uuid()
})

export const updateQuestionApiV1QuestionsQuestionIdPatchBodyTimeLimitMsOneExclusiveMin = 0;

export const updateQuestionApiV1QuestionsQuestionIdPatchBodyMemoryLimitMbOneExclusiveMin = 0;



export const UpdateQuestionApiV1QuestionsQuestionIdPatchBody = zod.object({
  "question_text": zod.union([zod.string(),zod.null()]).optional(),
  "difficulty": zod.union([zod.enum(['EASY', 'MEDIUM', 'HARD']).describe('Enumeration of question difficulty levels for contest problems.\n\nUsed to categorize problems by their complexity and expected\nsolving time to help with contest balancing and participant preparation.\n\nAttributes:\n    EASY: Basic problems suitable for beginners, typically solvable in 15-30 minutes.\n    MEDIUM: Intermediate problems requiring algorithmic thinking, 30-60 minutes.\n    HARD: Advanced problems demanding complex algorithms, 60+ minutes.'),zod.null()]).optional(),
  "allowed_languages": zod.union([zod.array(zod.string()),zod.null()]).optional(),
  "testcases": zod.union([zod.array(zod.record(zod.string(), zod.unknown())),zod.null()]).optional(),
  "time_limit_ms": zod.union([zod.number().gt(updateQuestionApiV1QuestionsQuestionIdPatchBodyTimeLimitMsOneExclusiveMin),zod.null()]).optional(),
  "memory_limit_mb": zod.union([zod.number().gt(updateQuestionApiV1QuestionsQuestionIdPatchBodyMemoryLimitMbOneExclusiveMin),zod.null()]).optional()
})

export const UpdateQuestionApiV1QuestionsQuestionIdPatchResponse = zod.unknown()

/**
 * Delete a question by ID.

Args:
    request: FastAPI request object
    question_id: ID of the question
    current_user: Dictionary holding keycloak JWT claims
    db: Injected database session
    service: Injected QuestionService

Raises:
    QuestionNotFoundError: If the question does not exist
    QuestionPermissionError: If user lacks management permissions
 * @summary Delete Question
 */
export const DeleteQuestionApiV1QuestionsQuestionIdDeleteParams = zod.object({
  "question_id": zod.uuid()
})

