/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Create a new contest.

Args:
    request (Request): Framework context.
    contest (ContestCreate): The contest data to create.
    user_id (UUID): The currently authenticated user ID via Keycloak.
    service (ContestService): Injected domain service handling contest operations.

Returns:
    APIResponse: Standardized response encapsulating creation metadata.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks create permission.
    RequestValidationError: If request payload validation fails.
    ContestAlreadyExistsError: If a contest with the same name already exists.
    InvalidContestError: If contest business validation fails.
    ContestOperationError: If contest creation fails unexpectedly.
 * @summary Create a new contest
 */
export const createContestApiV1ContestsPostBodyNameMax = 255;

export const createContestApiV1ContestsPostBodyDescriptionOneMax = 5000;

export const createContestApiV1ContestsPostBodyIsPublicDefault = false;
export const createContestApiV1ContestsPostBodyMinTeamSizeDefault = 1;
export const createContestApiV1ContestsPostBodyMaxTeamSizeDefault = 1;
export const createContestApiV1ContestsPostBodyScoringTypeDefault = `AUTO`;

export const CreateContestApiV1ContestsPostBody = zod.object({
  "name": zod.string().min(1).max(createContestApiV1ContestsPostBodyNameMax).describe('Contest name'),
  "description": zod.union([zod.string().max(createContestApiV1ContestsPostBodyDescriptionOneMax),zod.null()]).optional().describe('Contest description'),
  "image": zod.union([zod.string(),zod.null()]).optional().describe('Contest image URL'),
  "is_public": zod.boolean().default(createContestApiV1ContestsPostBodyIsPublicDefault).describe('Whether contest is public'),
  "start_time": zod.iso.datetime({}).describe('Contest start time (UTC)'),
  "end_time": zod.iso.datetime({}).describe('Contest end time (UTC)'),
  "registration_start": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration start time (UTC)'),
  "registration_end": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration end time (UTC)'),
  "max_teams": zod.union([zod.number(),zod.null()]).optional().describe('Maximum number of teams allowed'),
  "min_team_size": zod.number().default(createContestApiV1ContestsPostBodyMinTeamSizeDefault).describe('Minimum team size'),
  "max_team_size": zod.number().default(createContestApiV1ContestsPostBodyMaxTeamSizeDefault).describe('Maximum team size'),
  "rules": zod.union([zod.string(),zod.null()]).optional().describe('Contest rules'),
  "scoring_type": zod.enum(['AUTO', 'MANUAL', 'HYBRID']).default(createContestApiV1ContestsPostBodyScoringTypeDefault).describe('Scoring type')
}).describe('Schema for creating a contest.')

/**
 * Get all active contests accessible to the user.

Args:
    request (Request): Framework context.
    user_id (UUID): Authenticated user ID.
    search (str | None): Optional string to search contest names.
    contest_status (ContestStatus | None): Optional filter for contest status.
    is_public (bool | None): Optional filter for visibility.
    page (int): Page number (starts from 1).
    page_size (int): Number of contests per page.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the list of contests and pagination state.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks read permission.
    RequestValidationError: If query parameter validation fails.
    ContestOperationError: If contest retrieval fails unexpectedly.
 * @summary Get all contests
 */
export const getAllContestsApiV1ContestsGetQueryPageDefault = 1;

export const getAllContestsApiV1ContestsGetQueryPageSizeDefault = 10;
export const getAllContestsApiV1ContestsGetQueryPageSizeMax = 100;



export const GetAllContestsApiV1ContestsGetQueryParams = zod.object({
  "search": zod.union([zod.string(),zod.null()]).optional().describe('Search by contest name'),
  "contest_status": zod.union([zod.enum(['DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'FINISHED', 'CANCELLED']).describe('Enumeration of contest lifecycle statuses.\n\nTracks the current state of a contest from creation through completion,\ncontrolling participant access and available operations.\n\nAttributes:\n    DRAFT: Contest is being configured and not visible to participants.\n    SCHEDULED: Contest is published and scheduled for future start.\n    RUNNING: Contest is currently active and accepting submissions.\n    PAUSED: Contest is temporarily halted, submissions disabled.\n    FINISHED: Contest has concluded, final results available.\n    CANCELLED: Contest has been cancelled and will not proceed.'),zod.null()]).optional().describe('Filter by contest status'),
  "is_public": zod.union([zod.boolean(),zod.null()]).optional().describe('Filter by visibility (public\/private)'),
  "page": zod.number().min(1).default(getAllContestsApiV1ContestsGetQueryPageDefault).describe('Page number (starts from 1)'),
  "page_size": zod.number().min(1).max(getAllContestsApiV1ContestsGetQueryPageSizeMax).default(getAllContestsApiV1ContestsGetQueryPageSizeDefault).describe('Number of contests per page')
})

export const getAllContestsApiV1ContestsGetResponseSuccessDefault = true;
export const getAllContestsApiV1ContestsGetResponseStatusDefault = 200;
export const getAllContestsApiV1ContestsGetResponseMessageDefault = `Success`;

export const GetAllContestsApiV1ContestsGetResponse = zod.object({
  "success": zod.boolean().default(getAllContestsApiV1ContestsGetResponseSuccessDefault),
  "status": zod.number().default(getAllContestsApiV1ContestsGetResponseStatusDefault),
  "message": zod.string().default(getAllContestsApiV1ContestsGetResponseMessageDefault),
  "data": zod.union([zod.array(zod.object({
  "id": zod.uuid().describe('Contest ID'),
  "name": zod.string().describe('Contest name'),
  "description": zod.union([zod.string(),zod.null()]).optional().describe('Contest description'),
  "image": zod.union([zod.string(),zod.null()]).optional().describe('Contest image URL'),
  "start_time": zod.iso.datetime({}).describe('Contest start time (UTC)'),
  "end_time": zod.iso.datetime({}).describe('Contest end time (UTC)'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'FINISHED', 'CANCELLED']).describe('Contest status'),
  "created_at": zod.iso.datetime({}).describe('Contest creation time (UTC)'),
  "is_public": zod.boolean().describe('Whether contest is public')
}).describe('Schema for contest summary response (List view).')),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Get soft-deleted contests accessible to the user.

Args:
    request (Request): Framework context.
    user_id (UUID): Authenticated user ID.
    search (str | None): Optional string to search contest names.
    contest_status (ContestStatus | None): Optional filter for contest status.
    page (int): Page number (starts from 1).
    page_size (int): Number of contests per page.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the list of soft-deleted contests.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks read permission.
    RequestValidationError: If query parameter validation fails.
    ContestOperationError: If contest retrieval fails unexpectedly.
 * @summary Get soft-deleted contests
 */
export const getDeletedContestsApiV1ContestsDeletedGetQueryPageDefault = 1;

export const getDeletedContestsApiV1ContestsDeletedGetQueryPageSizeDefault = 10;
export const getDeletedContestsApiV1ContestsDeletedGetQueryPageSizeMax = 100;



export const GetDeletedContestsApiV1ContestsDeletedGetQueryParams = zod.object({
  "search": zod.union([zod.string(),zod.null()]).optional().describe('Search by contest name'),
  "contest_status": zod.union([zod.enum(['DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'FINISHED', 'CANCELLED']).describe('Enumeration of contest lifecycle statuses.\n\nTracks the current state of a contest from creation through completion,\ncontrolling participant access and available operations.\n\nAttributes:\n    DRAFT: Contest is being configured and not visible to participants.\n    SCHEDULED: Contest is published and scheduled for future start.\n    RUNNING: Contest is currently active and accepting submissions.\n    PAUSED: Contest is temporarily halted, submissions disabled.\n    FINISHED: Contest has concluded, final results available.\n    CANCELLED: Contest has been cancelled and will not proceed.'),zod.null()]).optional().describe('Filter by contest status'),
  "page": zod.number().min(1).default(getDeletedContestsApiV1ContestsDeletedGetQueryPageDefault).describe('Page number (starts from 1)'),
  "page_size": zod.number().min(1).max(getDeletedContestsApiV1ContestsDeletedGetQueryPageSizeMax).default(getDeletedContestsApiV1ContestsDeletedGetQueryPageSizeDefault).describe('Number of contests per page')
})

export const getDeletedContestsApiV1ContestsDeletedGetResponseSuccessDefault = true;
export const getDeletedContestsApiV1ContestsDeletedGetResponseStatusDefault = 200;
export const getDeletedContestsApiV1ContestsDeletedGetResponseMessageDefault = `Success`;

export const GetDeletedContestsApiV1ContestsDeletedGetResponse = zod.object({
  "success": zod.boolean().default(getDeletedContestsApiV1ContestsDeletedGetResponseSuccessDefault),
  "status": zod.number().default(getDeletedContestsApiV1ContestsDeletedGetResponseStatusDefault),
  "message": zod.string().default(getDeletedContestsApiV1ContestsDeletedGetResponseMessageDefault),
  "data": zod.union([zod.array(zod.object({
  "id": zod.uuid().describe('Contest ID'),
  "name": zod.string().describe('Contest name'),
  "description": zod.union([zod.string(),zod.null()]).optional().describe('Contest description'),
  "image": zod.union([zod.string(),zod.null()]).optional().describe('Contest image URL'),
  "start_time": zod.iso.datetime({}).describe('Contest start time (UTC)'),
  "end_time": zod.iso.datetime({}).describe('Contest end time (UTC)'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'FINISHED', 'CANCELLED']).describe('Contest status'),
  "created_at": zod.iso.datetime({}).describe('Contest creation time (UTC)'),
  "is_public": zod.boolean().describe('Whether contest is public')
}).describe('Schema for contest summary response (List view).')),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Get detailed information about a specific contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    service (ContestService): Injected domain service.
    user_id (UUID): Authenticated user ID.

Returns:
    APIResponse: Detailed information block for the contest.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks read permission.
    ContestNotFoundError: If the contest does not exist.
    ContestOperationError: If contest retrieval fails unexpectedly.
 * @summary Get contest by ID
 */
export const GetContestApiV1ContestsContestIdGetParams = zod.object({
  "contest_id": zod.uuid()
})

export const getContestApiV1ContestsContestIdGetResponseSuccessDefault = true;
export const getContestApiV1ContestsContestIdGetResponseStatusDefault = 200;
export const getContestApiV1ContestsContestIdGetResponseMessageDefault = `Success`;
export const getContestApiV1ContestsContestIdGetResponseDataOneNameMax = 255;

export const getContestApiV1ContestsContestIdGetResponseDataOneDescriptionOneMax = 5000;

export const getContestApiV1ContestsContestIdGetResponseDataOneIsPublicDefault = false;
export const getContestApiV1ContestsContestIdGetResponseDataOneMinTeamSizeDefault = 1;
export const getContestApiV1ContestsContestIdGetResponseDataOneMaxTeamSizeDefault = 1;
export const getContestApiV1ContestsContestIdGetResponseDataOneScoringTypeDefault = `AUTO`;

export const GetContestApiV1ContestsContestIdGetResponse = zod.object({
  "success": zod.boolean().default(getContestApiV1ContestsContestIdGetResponseSuccessDefault),
  "status": zod.number().default(getContestApiV1ContestsContestIdGetResponseStatusDefault),
  "message": zod.string().default(getContestApiV1ContestsContestIdGetResponseMessageDefault),
  "data": zod.union([zod.object({
  "name": zod.string().min(1).max(getContestApiV1ContestsContestIdGetResponseDataOneNameMax).describe('Contest name'),
  "description": zod.union([zod.string().max(getContestApiV1ContestsContestIdGetResponseDataOneDescriptionOneMax),zod.null()]).optional().describe('Contest description'),
  "image": zod.union([zod.string(),zod.null()]).optional().describe('Contest image URL'),
  "is_public": zod.boolean().default(getContestApiV1ContestsContestIdGetResponseDataOneIsPublicDefault).describe('Whether contest is public'),
  "start_time": zod.iso.datetime({}).describe('Contest start time (UTC)'),
  "end_time": zod.iso.datetime({}).describe('Contest end time (UTC)'),
  "registration_start": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration start time (UTC)'),
  "registration_end": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration end time (UTC)'),
  "max_teams": zod.union([zod.number(),zod.null()]).optional().describe('Maximum number of teams allowed'),
  "min_team_size": zod.number().default(getContestApiV1ContestsContestIdGetResponseDataOneMinTeamSizeDefault).describe('Minimum team size'),
  "max_team_size": zod.number().default(getContestApiV1ContestsContestIdGetResponseDataOneMaxTeamSizeDefault).describe('Maximum team size'),
  "rules": zod.union([zod.string(),zod.null()]).optional().describe('Contest rules'),
  "scoring_type": zod.enum(['AUTO', 'MANUAL', 'HYBRID']).default(getContestApiV1ContestsContestIdGetResponseDataOneScoringTypeDefault).describe('Scoring type'),
  "id": zod.uuid().describe('Contest ID'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'FINISHED', 'CANCELLED']).describe('Contest status'),
  "created_by": zod.uuid().describe('Creator user ID'),
  "creator": zod.union([zod.object({
  "id": zod.uuid().describe('Instructor ID'),
  "user_id": zod.string().describe('Instructor user ID'),
  "name": zod.string().describe('Instructor name'),
  "email": zod.string().describe('Instructor email'),
  "phone_no": zod.union([zod.string(),zod.null()]).optional().describe('Instructor phone number'),
  "role": zod.string().describe('Instructor role'),
  "gender": zod.union([zod.string(),zod.null()]).optional().describe('Instructor gender'),
  "dob": zod.union([zod.iso.date(),zod.null()]).optional().describe('Instructor date of birth'),
  "created_at": zod.iso.datetime({}).describe('Account creation time (UTC)')
}).describe('Schema for instructor response.'),zod.null()]).optional().describe('Creator details'),
  "created_at": zod.iso.datetime({}).describe('Contest creation time (UTC)'),
  "updated_at": zod.iso.datetime({}).describe('Last update time (UTC)'),
  "updated_by": zod.union([zod.uuid(),zod.null()]).optional().describe('User ID who last updated'),
  "show_leaderboard": zod.boolean().describe('Whether leaderboard is shown'),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Published time (UTC)'),
  "published_by": zod.union([zod.uuid(),zod.null()]).optional().describe('User ID who published the contest')
}).describe('Schema for comprehensive contest response (Detail view).'),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Update contest details.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    contest_data (ContestUpdate): The fields to update.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the updated contest details.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    RequestValidationError: If request payload validation fails.
    ContestNotFoundError: If the contest does not exist.
    InvalidContestError: If contest business validation fails.
    ContestOperationError: If contest update fails unexpectedly.
 * @summary Update contest
 */
export const UpdateContestApiV1ContestsContestIdPatchParams = zod.object({
  "contest_id": zod.uuid()
})

export const updateContestApiV1ContestsContestIdPatchBodyNameOneMax = 255;

export const updateContestApiV1ContestsContestIdPatchBodyDescriptionOneMax = 5000;



export const UpdateContestApiV1ContestsContestIdPatchBody = zod.object({
  "name": zod.union([zod.string().min(1).max(updateContestApiV1ContestsContestIdPatchBodyNameOneMax),zod.null()]).optional().describe('Contest name'),
  "description": zod.union([zod.string().max(updateContestApiV1ContestsContestIdPatchBodyDescriptionOneMax),zod.null()]).optional().describe('Contest description'),
  "image": zod.union([zod.string(),zod.null()]).optional().describe('Contest image URL'),
  "is_public": zod.union([zod.boolean(),zod.null()]).optional().describe('Whether contest is public'),
  "start_time": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Contest start time (UTC)'),
  "end_time": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Contest end time (UTC)'),
  "registration_start": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration start time (UTC)'),
  "registration_end": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration end time (UTC)'),
  "max_teams": zod.union([zod.number(),zod.null()]).optional().describe('Maximum number of teams allowed'),
  "min_team_size": zod.union([zod.number(),zod.null()]).optional().describe('Minimum team size'),
  "max_team_size": zod.union([zod.number(),zod.null()]).optional().describe('Maximum team size'),
  "rules": zod.union([zod.string(),zod.null()]).optional().describe('Contest rules'),
  "scoring_type": zod.union([zod.enum(['AUTO', 'MANUAL', 'HYBRID']).describe('Enumeration of scoring methods for contest evaluation.\n\nDetermines how submissions are evaluated and scored during contests,\naffecting the judging workflow and result calculation.\n\nAttributes:\n    AUTO: Fully automatic scoring using predefined test cases and judges.\n    MANUAL: Human-reviewed scoring for subjective or complex evaluation.\n    HYBRID: Combined automatic and manual scoring for comprehensive assessment.'),zod.null()]).optional().describe('Scoring type'),
  "show_leaderboard": zod.union([zod.boolean(),zod.null()]).optional().describe('Whether to show leaderboard')
}).describe('Schema for updating a contest.')

export const updateContestApiV1ContestsContestIdPatchResponseSuccessDefault = true;
export const updateContestApiV1ContestsContestIdPatchResponseStatusDefault = 200;
export const updateContestApiV1ContestsContestIdPatchResponseMessageDefault = `Success`;
export const updateContestApiV1ContestsContestIdPatchResponseDataOneNameMax = 255;

export const updateContestApiV1ContestsContestIdPatchResponseDataOneDescriptionOneMax = 5000;

export const updateContestApiV1ContestsContestIdPatchResponseDataOneIsPublicDefault = false;
export const updateContestApiV1ContestsContestIdPatchResponseDataOneMinTeamSizeDefault = 1;
export const updateContestApiV1ContestsContestIdPatchResponseDataOneMaxTeamSizeDefault = 1;
export const updateContestApiV1ContestsContestIdPatchResponseDataOneScoringTypeDefault = `AUTO`;

export const UpdateContestApiV1ContestsContestIdPatchResponse = zod.object({
  "success": zod.boolean().default(updateContestApiV1ContestsContestIdPatchResponseSuccessDefault),
  "status": zod.number().default(updateContestApiV1ContestsContestIdPatchResponseStatusDefault),
  "message": zod.string().default(updateContestApiV1ContestsContestIdPatchResponseMessageDefault),
  "data": zod.union([zod.object({
  "name": zod.string().min(1).max(updateContestApiV1ContestsContestIdPatchResponseDataOneNameMax).describe('Contest name'),
  "description": zod.union([zod.string().max(updateContestApiV1ContestsContestIdPatchResponseDataOneDescriptionOneMax),zod.null()]).optional().describe('Contest description'),
  "image": zod.union([zod.string(),zod.null()]).optional().describe('Contest image URL'),
  "is_public": zod.boolean().default(updateContestApiV1ContestsContestIdPatchResponseDataOneIsPublicDefault).describe('Whether contest is public'),
  "start_time": zod.iso.datetime({}).describe('Contest start time (UTC)'),
  "end_time": zod.iso.datetime({}).describe('Contest end time (UTC)'),
  "registration_start": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration start time (UTC)'),
  "registration_end": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration end time (UTC)'),
  "max_teams": zod.union([zod.number(),zod.null()]).optional().describe('Maximum number of teams allowed'),
  "min_team_size": zod.number().default(updateContestApiV1ContestsContestIdPatchResponseDataOneMinTeamSizeDefault).describe('Minimum team size'),
  "max_team_size": zod.number().default(updateContestApiV1ContestsContestIdPatchResponseDataOneMaxTeamSizeDefault).describe('Maximum team size'),
  "rules": zod.union([zod.string(),zod.null()]).optional().describe('Contest rules'),
  "scoring_type": zod.enum(['AUTO', 'MANUAL', 'HYBRID']).default(updateContestApiV1ContestsContestIdPatchResponseDataOneScoringTypeDefault).describe('Scoring type'),
  "id": zod.uuid().describe('Contest ID'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'FINISHED', 'CANCELLED']).describe('Contest status'),
  "created_by": zod.uuid().describe('Creator user ID'),
  "creator": zod.union([zod.object({
  "id": zod.uuid().describe('Instructor ID'),
  "user_id": zod.string().describe('Instructor user ID'),
  "name": zod.string().describe('Instructor name'),
  "email": zod.string().describe('Instructor email'),
  "phone_no": zod.union([zod.string(),zod.null()]).optional().describe('Instructor phone number'),
  "role": zod.string().describe('Instructor role'),
  "gender": zod.union([zod.string(),zod.null()]).optional().describe('Instructor gender'),
  "dob": zod.union([zod.iso.date(),zod.null()]).optional().describe('Instructor date of birth'),
  "created_at": zod.iso.datetime({}).describe('Account creation time (UTC)')
}).describe('Schema for instructor response.'),zod.null()]).optional().describe('Creator details'),
  "created_at": zod.iso.datetime({}).describe('Contest creation time (UTC)'),
  "updated_at": zod.iso.datetime({}).describe('Last update time (UTC)'),
  "updated_by": zod.union([zod.uuid(),zod.null()]).optional().describe('User ID who last updated'),
  "show_leaderboard": zod.boolean().describe('Whether leaderboard is shown'),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Published time (UTC)'),
  "published_by": zod.union([zod.uuid(),zod.null()]).optional().describe('User ID who published the contest')
}).describe('Schema for comprehensive contest response (Detail view).'),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Hard delete a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest to delete.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks delete permission.
    ContestNotFoundError: If the contest does not exist.
    ContestOperationError: If contest deletion fails unexpectedly.
 * @summary Delete contest
 */
export const DeleteContestApiV1ContestsContestIdDeleteParams = zod.object({
  "contest_id": zod.uuid()
})

export const deleteContestApiV1ContestsContestIdDeleteResponseSuccessDefault = true;
export const deleteContestApiV1ContestsContestIdDeleteResponseStatusDefault = 200;
export const deleteContestApiV1ContestsContestIdDeleteResponseMessageDefault = `Success`;

export const DeleteContestApiV1ContestsContestIdDeleteResponse = zod.object({
  "success": zod.boolean().default(deleteContestApiV1ContestsContestIdDeleteResponseSuccessDefault),
  "status": zod.number().default(deleteContestApiV1ContestsContestIdDeleteResponseStatusDefault),
  "message": zod.string().default(deleteContestApiV1ContestsContestIdDeleteResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Publish a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest to publish.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    ContestNotFoundError: If the contest does not exist.
    InvalidContestError: If contest cannot be published in its current state.
    ContestOperationError: If contest publish fails unexpectedly.
 * @summary Publish contest
 */
export const PublishContestApiV1ContestsContestIdPublishPostParams = zod.object({
  "contest_id": zod.uuid()
})

export const publishContestApiV1ContestsContestIdPublishPostResponseSuccessDefault = true;
export const publishContestApiV1ContestsContestIdPublishPostResponseStatusDefault = 200;
export const publishContestApiV1ContestsContestIdPublishPostResponseMessageDefault = `Success`;

export const PublishContestApiV1ContestsContestIdPublishPostResponse = zod.object({
  "success": zod.boolean().default(publishContestApiV1ContestsContestIdPublishPostResponseSuccessDefault),
  "status": zod.number().default(publishContestApiV1ContestsContestIdPublishPostResponseStatusDefault),
  "message": zod.string().default(publishContestApiV1ContestsContestIdPublishPostResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Soft delete a contest without physically removing it.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest to soft delete.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks delete permission.
    ContestNotFoundError: If the contest does not exist.
    ContestOperationError: If contest soft deletion fails unexpectedly.
 * @summary Soft delete contest
 */
export const SoftDeleteContestApiV1ContestsContestIdSoftDeleteDeleteParams = zod.object({
  "contest_id": zod.uuid()
})

export const softDeleteContestApiV1ContestsContestIdSoftDeleteDeleteResponseSuccessDefault = true;
export const softDeleteContestApiV1ContestsContestIdSoftDeleteDeleteResponseStatusDefault = 200;
export const softDeleteContestApiV1ContestsContestIdSoftDeleteDeleteResponseMessageDefault = `Success`;

export const SoftDeleteContestApiV1ContestsContestIdSoftDeleteDeleteResponse = zod.object({
  "success": zod.boolean().default(softDeleteContestApiV1ContestsContestIdSoftDeleteDeleteResponseSuccessDefault),
  "status": zod.number().default(softDeleteContestApiV1ContestsContestIdSoftDeleteDeleteResponseStatusDefault),
  "message": zod.string().default(softDeleteContestApiV1ContestsContestIdSoftDeleteDeleteResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Restore a soft-deleted contest.

Returns the contest to an active status.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest to restore.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the restored contest data.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    ContestNotFoundError: If the contest does not exist.
    InvalidContestError: If contest cannot be restored in its current state.
    ContestOperationError: If contest restoration fails unexpectedly.
 * @summary Restore soft-deleted contest
 */
export const RestoreContestApiV1ContestsContestIdRestorePostParams = zod.object({
  "contest_id": zod.uuid()
})

export const restoreContestApiV1ContestsContestIdRestorePostResponseSuccessDefault = true;
export const restoreContestApiV1ContestsContestIdRestorePostResponseStatusDefault = 200;
export const restoreContestApiV1ContestsContestIdRestorePostResponseMessageDefault = `Success`;
export const restoreContestApiV1ContestsContestIdRestorePostResponseDataOneNameMax = 255;

export const restoreContestApiV1ContestsContestIdRestorePostResponseDataOneDescriptionOneMax = 5000;

export const restoreContestApiV1ContestsContestIdRestorePostResponseDataOneIsPublicDefault = false;
export const restoreContestApiV1ContestsContestIdRestorePostResponseDataOneMinTeamSizeDefault = 1;
export const restoreContestApiV1ContestsContestIdRestorePostResponseDataOneMaxTeamSizeDefault = 1;
export const restoreContestApiV1ContestsContestIdRestorePostResponseDataOneScoringTypeDefault = `AUTO`;

export const RestoreContestApiV1ContestsContestIdRestorePostResponse = zod.object({
  "success": zod.boolean().default(restoreContestApiV1ContestsContestIdRestorePostResponseSuccessDefault),
  "status": zod.number().default(restoreContestApiV1ContestsContestIdRestorePostResponseStatusDefault),
  "message": zod.string().default(restoreContestApiV1ContestsContestIdRestorePostResponseMessageDefault),
  "data": zod.union([zod.object({
  "name": zod.string().min(1).max(restoreContestApiV1ContestsContestIdRestorePostResponseDataOneNameMax).describe('Contest name'),
  "description": zod.union([zod.string().max(restoreContestApiV1ContestsContestIdRestorePostResponseDataOneDescriptionOneMax),zod.null()]).optional().describe('Contest description'),
  "image": zod.union([zod.string(),zod.null()]).optional().describe('Contest image URL'),
  "is_public": zod.boolean().default(restoreContestApiV1ContestsContestIdRestorePostResponseDataOneIsPublicDefault).describe('Whether contest is public'),
  "start_time": zod.iso.datetime({}).describe('Contest start time (UTC)'),
  "end_time": zod.iso.datetime({}).describe('Contest end time (UTC)'),
  "registration_start": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration start time (UTC)'),
  "registration_end": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Registration end time (UTC)'),
  "max_teams": zod.union([zod.number(),zod.null()]).optional().describe('Maximum number of teams allowed'),
  "min_team_size": zod.number().default(restoreContestApiV1ContestsContestIdRestorePostResponseDataOneMinTeamSizeDefault).describe('Minimum team size'),
  "max_team_size": zod.number().default(restoreContestApiV1ContestsContestIdRestorePostResponseDataOneMaxTeamSizeDefault).describe('Maximum team size'),
  "rules": zod.union([zod.string(),zod.null()]).optional().describe('Contest rules'),
  "scoring_type": zod.enum(['AUTO', 'MANUAL', 'HYBRID']).default(restoreContestApiV1ContestsContestIdRestorePostResponseDataOneScoringTypeDefault).describe('Scoring type'),
  "id": zod.uuid().describe('Contest ID'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'FINISHED', 'CANCELLED']).describe('Contest status'),
  "created_by": zod.uuid().describe('Creator user ID'),
  "creator": zod.union([zod.object({
  "id": zod.uuid().describe('Instructor ID'),
  "user_id": zod.string().describe('Instructor user ID'),
  "name": zod.string().describe('Instructor name'),
  "email": zod.string().describe('Instructor email'),
  "phone_no": zod.union([zod.string(),zod.null()]).optional().describe('Instructor phone number'),
  "role": zod.string().describe('Instructor role'),
  "gender": zod.union([zod.string(),zod.null()]).optional().describe('Instructor gender'),
  "dob": zod.union([zod.iso.date(),zod.null()]).optional().describe('Instructor date of birth'),
  "created_at": zod.iso.datetime({}).describe('Account creation time (UTC)')
}).describe('Schema for instructor response.'),zod.null()]).optional().describe('Creator details'),
  "created_at": zod.iso.datetime({}).describe('Contest creation time (UTC)'),
  "updated_at": zod.iso.datetime({}).describe('Last update time (UTC)'),
  "updated_by": zod.union([zod.uuid(),zod.null()]).optional().describe('User ID who last updated'),
  "show_leaderboard": zod.boolean().describe('Whether leaderboard is shown'),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional().describe('Published time (UTC)'),
  "published_by": zod.union([zod.uuid(),zod.null()]).optional().describe('User ID who published the contest')
}).describe('Schema for comprehensive contest response (Detail view).'),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Assign instructors to a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    instructor_request (InstructorManageRequest): Request containing instructor IDs.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    RequestValidationError: If request payload validation fails.
    ContestNotFoundError: If the contest does not exist.
    InstructorNotFoundError: If an instructor ID is invalid.
    InstructorAlreadyAssignedError: If an instructor is already assigned.
    ContestOperationError: If instructor assignment fails unexpectedly.
 * @summary Assign instructors to contest
 */
export const AssignInstructorsToContestApiV1ContestsContestIdInstructorsPostParams = zod.object({
  "contest_id": zod.uuid()
})

export const AssignInstructorsToContestApiV1ContestsContestIdInstructorsPostBody = zod.object({
  "instructor_ids": zod.array(zod.uuid()).describe('List of instructor IDs to assign or remove')
}).describe('Schema for managing instructors in a contest.')

export const assignInstructorsToContestApiV1ContestsContestIdInstructorsPostResponseSuccessDefault = true;
export const assignInstructorsToContestApiV1ContestsContestIdInstructorsPostResponseStatusDefault = 200;
export const assignInstructorsToContestApiV1ContestsContestIdInstructorsPostResponseMessageDefault = `Success`;

export const AssignInstructorsToContestApiV1ContestsContestIdInstructorsPostResponse = zod.object({
  "success": zod.boolean().default(assignInstructorsToContestApiV1ContestsContestIdInstructorsPostResponseSuccessDefault),
  "status": zod.number().default(assignInstructorsToContestApiV1ContestsContestIdInstructorsPostResponseStatusDefault),
  "message": zod.string().default(assignInstructorsToContestApiV1ContestsContestIdInstructorsPostResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Remove instructors from a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    instructor_request (InstructorManageRequest): Request containing instructor IDs to remove.
    user_id (UUID): Authenticated user ID.
    service (ContestService): Injected domain service.

Returns:
    APIResponse: Success confirmation.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks update permission.
    RequestValidationError: If request payload validation fails.
    ContestNotFoundError: If the contest does not exist.
    InstructorNotAssignedError: If an instructor is not currently assigned.
    ContestOperationError: If instructor removal fails unexpectedly.
 * @summary Remove instructors from contest
 */
export const RemoveInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteParams = zod.object({
  "contest_id": zod.uuid()
})

export const RemoveInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteBody = zod.object({
  "instructor_ids": zod.array(zod.uuid()).describe('List of instructor IDs to assign or remove')
}).describe('Schema for managing instructors in a contest.')

export const removeInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteResponseSuccessDefault = true;
export const removeInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteResponseStatusDefault = 200;
export const removeInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteResponseMessageDefault = `Success`;

export const RemoveInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteResponse = zod.object({
  "success": zod.boolean().default(removeInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteResponseSuccessDefault),
  "status": zod.number().default(removeInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteResponseStatusDefault),
  "message": zod.string().default(removeInstructorsFromContestApiV1ContestsContestIdInstructorsDeleteResponseMessageDefault),
  "data": zod.union([zod.unknown(),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

/**
 * Get paginated list of instructors for a contest.

Args:
    request (Request): Framework context.
    contest_id (UUID): The unique identifier of the contest.
    page (int): Page number (starts from 1).
    page_size (int): Number of instructors per page.
    service (ContestService): Injected domain service.
    user_id (UUID): Authenticated user ID.

Returns:
    APIResponse: Standardized response with list of instructors and pagination state.

Raises:
    UnauthorizedError: If the caller is not authenticated.
    PermissionDeniedError: If the caller lacks read permission.
    RequestValidationError: If query parameter validation fails.
    ContestNotFoundError: If the contest does not exist.
    ContestOperationError: If instructor retrieval fails unexpectedly.
 * @summary Get contest instructors
 */
export const GetContestInstructorsApiV1ContestsContestIdInstructorsGetParams = zod.object({
  "contest_id": zod.uuid()
})

export const getContestInstructorsApiV1ContestsContestIdInstructorsGetQueryPageDefault = 1;

export const getContestInstructorsApiV1ContestsContestIdInstructorsGetQueryPageSizeDefault = 10;
export const getContestInstructorsApiV1ContestsContestIdInstructorsGetQueryPageSizeMax = 100;



export const GetContestInstructorsApiV1ContestsContestIdInstructorsGetQueryParams = zod.object({
  "page": zod.number().min(1).default(getContestInstructorsApiV1ContestsContestIdInstructorsGetQueryPageDefault).describe('Page number (starts from 1)'),
  "page_size": zod.number().min(1).max(getContestInstructorsApiV1ContestsContestIdInstructorsGetQueryPageSizeMax).default(getContestInstructorsApiV1ContestsContestIdInstructorsGetQueryPageSizeDefault).describe('Number of instructors per page')
})

export const getContestInstructorsApiV1ContestsContestIdInstructorsGetResponseSuccessDefault = true;
export const getContestInstructorsApiV1ContestsContestIdInstructorsGetResponseStatusDefault = 200;
export const getContestInstructorsApiV1ContestsContestIdInstructorsGetResponseMessageDefault = `Success`;

export const GetContestInstructorsApiV1ContestsContestIdInstructorsGetResponse = zod.object({
  "success": zod.boolean().default(getContestInstructorsApiV1ContestsContestIdInstructorsGetResponseSuccessDefault),
  "status": zod.number().default(getContestInstructorsApiV1ContestsContestIdInstructorsGetResponseStatusDefault),
  "message": zod.string().default(getContestInstructorsApiV1ContestsContestIdInstructorsGetResponseMessageDefault),
  "data": zod.union([zod.array(zod.object({
  "id": zod.uuid().describe('Instructor ID'),
  "user_id": zod.string().describe('Instructor user ID'),
  "name": zod.string().describe('Instructor name'),
  "email": zod.string().describe('Instructor email'),
  "phone_no": zod.union([zod.string(),zod.null()]).optional().describe('Instructor phone number'),
  "role": zod.string().describe('Instructor role'),
  "gender": zod.union([zod.string(),zod.null()]).optional().describe('Instructor gender'),
  "dob": zod.union([zod.iso.date(),zod.null()]).optional().describe('Instructor date of birth'),
  "created_at": zod.iso.datetime({}).describe('Account creation time (UTC)')
}).describe('Schema for instructor response.')),zod.null()]).optional(),
  "pagination": zod.union([zod.object({
  "total": zod.number(),
  "page": zod.number(),
  "page_size": zod.number(),
  "total_pages": zod.number(),
  "has_next": zod.boolean(),
  "has_previous": zod.boolean()
}),zod.null()]).optional(),
  "meta": zod.object({
  "request_id": zod.string(),
  "timestamp": zod.iso.datetime({})
})
})

