/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  APIResponse,
  APIResponseBankDetailResponse,
  APIResponseBankResponse,
  APIResponseListBankResponse,
  BankCreate,
  BankShareRequest,
  BankUnshareRequest,
  BankUpdate,
  ExceptionResponse,
  GetAllBanksApiV1BanksGetParams,
  GetDeletedBanksApiV1BanksDeletedGetParams,
  HTTPValidationError
} from '../../model';

import { axiosWithAuth } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new bank.

Args:
    request (Request): Framework context.
    bank (BankCreate): The bank data to create.
    user_id (UUID): The currently authenticated user ID via Keycloak.
    service (BankService): Injected domain service handling bank.

Returns:
    APIResponse: Standardized response encapsulating creation metadata.
 * @summary Create a new bank
 */
export const createBankApiV1BanksPost = (
    bankCreate: BankCreate,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/banks/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bankCreate, signal
    },
      options);
    }



export const getCreateBankApiV1BanksPostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBankApiV1BanksPost>>, TError,{data: BankCreate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof createBankApiV1BanksPost>>, TError,{data: BankCreate}, TContext> => {

const mutationKey = ['createBankApiV1BanksPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBankApiV1BanksPost>>, {data: BankCreate}> = (props) => {
          const {data} = props ?? {};

          return  createBankApiV1BanksPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateBankApiV1BanksPostMutationResult = NonNullable<Awaited<ReturnType<typeof createBankApiV1BanksPost>>>
    export type CreateBankApiV1BanksPostMutationBody = BankCreate
    export type CreateBankApiV1BanksPostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Create a new bank
 */
export const useCreateBankApiV1BanksPost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBankApiV1BanksPost>>, TError,{data: BankCreate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBankApiV1BanksPost>>,
        TError,
        {data: BankCreate},
        TContext
      > => {
      return useMutation(getCreateBankApiV1BanksPostMutationOptions(options), queryClient);
    }
    /**
 * Get all banks accessible to the user.

This includes banks created by the user and banks shared with the user.

Args:
    request (Request): Framework context.
    page (int): Page number (starts from 1).
    page_size (int): Number of banks per page.
    user_id (UUID): Authenticated user ID.
    service (BankService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the list of banks and pagination state.
 * @summary Get all banks
 */
export const getAllBanksApiV1BanksGet = (
    params?: GetAllBanksApiV1BanksGetParams,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseListBankResponse>(
      {url: `/api/v1/banks/`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetAllBanksApiV1BanksGetQueryKey = (params?: GetAllBanksApiV1BanksGetParams,) => {
    return [
    `/api/v1/banks/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllBanksApiV1BanksGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError = ExceptionResponse | HTTPValidationError>(params?: GetAllBanksApiV1BanksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllBanksApiV1BanksGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>> = ({ signal }) => getAllBanksApiV1BanksGet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllBanksApiV1BanksGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>>
export type GetAllBanksApiV1BanksGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetAllBanksApiV1BanksGet<TData = Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params: undefined |  GetAllBanksApiV1BanksGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>,
          TError,
          Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBanksApiV1BanksGet<TData = Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetAllBanksApiV1BanksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>,
          TError,
          Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBanksApiV1BanksGet<TData = Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetAllBanksApiV1BanksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all banks
 */

export function useGetAllBanksApiV1BanksGet<TData = Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetAllBanksApiV1BanksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBanksApiV1BanksGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllBanksApiV1BanksGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get all softly deleted banks accessible to the user.

Args:
    request (Request): Framework context.
    page (int): Page number (starts from 1).
    page_size (int): Number of banks per page.
    user_id (UUID): Authenticated user ID.
    service (BankService): Injected domain service.

Returns:
    APIResponse: Standardized response encapsulating the list of softly deleted banks.
 * @summary Get softly deleted banks
 */
export const getDeletedBanksApiV1BanksDeletedGet = (
    params?: GetDeletedBanksApiV1BanksDeletedGetParams,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseListBankResponse>(
      {url: `/api/v1/banks/deleted`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetDeletedBanksApiV1BanksDeletedGetQueryKey = (params?: GetDeletedBanksApiV1BanksDeletedGetParams,) => {
    return [
    `/api/v1/banks/deleted`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetDeletedBanksApiV1BanksDeletedGetQueryOptions = <TData = Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(params?: GetDeletedBanksApiV1BanksDeletedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeletedBanksApiV1BanksDeletedGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>> = ({ signal }) => getDeletedBanksApiV1BanksDeletedGet(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDeletedBanksApiV1BanksDeletedGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>>
export type GetDeletedBanksApiV1BanksDeletedGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetDeletedBanksApiV1BanksDeletedGet<TData = Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params: undefined |  GetDeletedBanksApiV1BanksDeletedGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>,
          TError,
          Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeletedBanksApiV1BanksDeletedGet<TData = Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetDeletedBanksApiV1BanksDeletedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>,
          TError,
          Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeletedBanksApiV1BanksDeletedGet<TData = Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetDeletedBanksApiV1BanksDeletedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get softly deleted banks
 */

export function useGetDeletedBanksApiV1BanksDeletedGet<TData = Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError = ExceptionResponse | HTTPValidationError>(
 params?: GetDeletedBanksApiV1BanksDeletedGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeletedBanksApiV1BanksDeletedGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDeletedBanksApiV1BanksDeletedGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get bank details including questions and shares.

Args:
    request (Request): Framework context.
    bank_id (UUID): The unique identifier of the bank.
    user_id (UUID): Authenticated user ID.
    service (BankService): Injected domain service.

Returns:
    APIResponse: Detailed information block for the bank.
 * @summary Get bank details
 */
export const getBankApiV1BanksBankIdGet = (
    bankId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseBankDetailResponse>(
      {url: `/api/v1/banks/${bankId}`, method: 'GET', signal
    },
      options);
    }




export const getGetBankApiV1BanksBankIdGetQueryKey = (bankId: string,) => {
    return [
    `/api/v1/banks/${bankId}`
    ] as const;
    }


export const getGetBankApiV1BanksBankIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError = ExceptionResponse | HTTPValidationError>(bankId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBankApiV1BanksBankIdGetQueryKey(bankId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>> = ({ signal }) => getBankApiV1BanksBankIdGet(bankId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(bankId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBankApiV1BanksBankIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>>
export type GetBankApiV1BanksBankIdGetQueryError = ExceptionResponse | HTTPValidationError


export function useGetBankApiV1BanksBankIdGet<TData = Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>,
          TError,
          Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBankApiV1BanksBankIdGet<TData = Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>,
          TError,
          Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBankApiV1BanksBankIdGet<TData = Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get bank details
 */

export function useGetBankApiV1BanksBankIdGet<TData = Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError = ExceptionResponse | HTTPValidationError>(
 bankId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBankApiV1BanksBankIdGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBankApiV1BanksBankIdGetQueryOptions(bankId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update bank details.

Only the owner or users with EDIT permission can update the bank.

Args:
    request (Request): Framework context.
    bank_id (UUID): The unique identifier of the bank.
    bank_update (BankUpdate): The fields to update.
    user_id (UUID): Authenticated user ID.
    service (BankService): Injected domain service.

Returns:
    APIResponse: Confirmation flag on update.
 * @summary Update bank
 */
export const updateBankApiV1BanksBankIdPatch = (
    bankId: string,
    bankUpdate: BankUpdate,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/banks/${bankId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: bankUpdate, signal
    },
      options);
    }



export const getUpdateBankApiV1BanksBankIdPatchMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBankApiV1BanksBankIdPatch>>, TError,{bankId: string;data: BankUpdate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBankApiV1BanksBankIdPatch>>, TError,{bankId: string;data: BankUpdate}, TContext> => {

const mutationKey = ['updateBankApiV1BanksBankIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBankApiV1BanksBankIdPatch>>, {bankId: string;data: BankUpdate}> = (props) => {
          const {bankId,data} = props ?? {};

          return  updateBankApiV1BanksBankIdPatch(bankId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateBankApiV1BanksBankIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateBankApiV1BanksBankIdPatch>>>
    export type UpdateBankApiV1BanksBankIdPatchMutationBody = BankUpdate
    export type UpdateBankApiV1BanksBankIdPatchMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Update bank
 */
export const useUpdateBankApiV1BanksBankIdPatch = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBankApiV1BanksBankIdPatch>>, TError,{bankId: string;data: BankUpdate}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBankApiV1BanksBankIdPatch>>,
        TError,
        {bankId: string;data: BankUpdate},
        TContext
      > => {
      return useMutation(getUpdateBankApiV1BanksBankIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete a bank.

Only the owner can delete the bank.

Args:
    request (Request): Framework context.
    bank_id (UUID): The unique identifier of the bank.
    user_id (UUID): Authenticated user ID.
    service (BankService): Injected domain service.

Returns:
    APIResponse: Success confirmation.
 * @summary Delete bank
 */
export const deleteBankApiV1BanksBankIdDelete = (
    bankId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/banks/${bankId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteBankApiV1BanksBankIdDeleteMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBankApiV1BanksBankIdDelete>>, TError,{bankId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBankApiV1BanksBankIdDelete>>, TError,{bankId: string}, TContext> => {

const mutationKey = ['deleteBankApiV1BanksBankIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBankApiV1BanksBankIdDelete>>, {bankId: string}> = (props) => {
          const {bankId} = props ?? {};

          return  deleteBankApiV1BanksBankIdDelete(bankId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteBankApiV1BanksBankIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBankApiV1BanksBankIdDelete>>>

    export type DeleteBankApiV1BanksBankIdDeleteMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Delete bank
 */
export const useDeleteBankApiV1BanksBankIdDelete = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBankApiV1BanksBankIdDelete>>, TError,{bankId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBankApiV1BanksBankIdDelete>>,
        TError,
        {bankId: string},
        TContext
      > => {
      return useMutation(getDeleteBankApiV1BanksBankIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Soft delete a bank without physically removing it.

Only the owner or authorized roles can manage this deletion status.

Args:
    request (Request): Framework context.
    bank_id (UUID): The unique identifier of the bank.
    user_id (UUID): Authenticated user ID.
    service (BankService): Injected domain service.

Returns:
    APIResponse: Success confirmation.
 * @summary Soft delete bank
 */
export const softDeleteBankApiV1BanksBankIdSoftDeleteDelete = (
    bankId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/banks/${bankId}/soft-delete`, method: 'DELETE', signal
    },
      options);
    }



export const getSoftDeleteBankApiV1BanksBankIdSoftDeleteDeleteMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof softDeleteBankApiV1BanksBankIdSoftDeleteDelete>>, TError,{bankId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof softDeleteBankApiV1BanksBankIdSoftDeleteDelete>>, TError,{bankId: string}, TContext> => {

const mutationKey = ['softDeleteBankApiV1BanksBankIdSoftDeleteDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof softDeleteBankApiV1BanksBankIdSoftDeleteDelete>>, {bankId: string}> = (props) => {
          const {bankId} = props ?? {};

          return  softDeleteBankApiV1BanksBankIdSoftDeleteDelete(bankId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SoftDeleteBankApiV1BanksBankIdSoftDeleteDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof softDeleteBankApiV1BanksBankIdSoftDeleteDelete>>>

    export type SoftDeleteBankApiV1BanksBankIdSoftDeleteDeleteMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Soft delete bank
 */
export const useSoftDeleteBankApiV1BanksBankIdSoftDeleteDelete = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof softDeleteBankApiV1BanksBankIdSoftDeleteDelete>>, TError,{bankId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof softDeleteBankApiV1BanksBankIdSoftDeleteDelete>>,
        TError,
        {bankId: string},
        TContext
      > => {
      return useMutation(getSoftDeleteBankApiV1BanksBankIdSoftDeleteDeleteMutationOptions(options), queryClient);
    }
    /**
 * Restore a softly deleted bank.

Returns the bank to an active status.

Args:
    request (Request): Framework context.
    bank_id (UUID): The unique identifier of the bank.
    user_id (UUID): Authenticated user ID.
    service (BankService): Injected domain service.

Returns:
    APIResponse: The restored bank object block.
 * @summary Restore softly deleted bank
 */
export const restoreBankApiV1BanksBankIdRestorePost = (
    bankId: string,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponseBankResponse>(
      {url: `/api/v1/banks/${bankId}/restore`, method: 'POST', signal
    },
      options);
    }



export const getRestoreBankApiV1BanksBankIdRestorePostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreBankApiV1BanksBankIdRestorePost>>, TError,{bankId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof restoreBankApiV1BanksBankIdRestorePost>>, TError,{bankId: string}, TContext> => {

const mutationKey = ['restoreBankApiV1BanksBankIdRestorePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreBankApiV1BanksBankIdRestorePost>>, {bankId: string}> = (props) => {
          const {bankId} = props ?? {};

          return  restoreBankApiV1BanksBankIdRestorePost(bankId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RestoreBankApiV1BanksBankIdRestorePostMutationResult = NonNullable<Awaited<ReturnType<typeof restoreBankApiV1BanksBankIdRestorePost>>>

    export type RestoreBankApiV1BanksBankIdRestorePostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Restore softly deleted bank
 */
export const useRestoreBankApiV1BanksBankIdRestorePost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreBankApiV1BanksBankIdRestorePost>>, TError,{bankId: string}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreBankApiV1BanksBankIdRestorePost>>,
        TError,
        {bankId: string},
        TContext
      > => {
      return useMutation(getRestoreBankApiV1BanksBankIdRestorePostMutationOptions(options), queryClient);
    }
    /**
 * Share bank with other users.

Only the owner can share the bank or transfer ownership.

Args:
    request (Request): Framework context.
    bank_id (UUID): The unique identifier of the bank.
    share_data (BankShareRequest): The list of users and permissions to share with.
    user_id (UUID): Authenticated user ID.
    service (BankService): Injected domain service.

Returns:
    APIResponse: Success confirmation on sharing execution.
 * @summary Share bank with users
 */
export const shareBankApiV1BanksBankIdSharePost = (
    bankId: string,
    bankShareRequest: BankShareRequest,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/banks/${bankId}/share`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bankShareRequest, signal
    },
      options);
    }



export const getShareBankApiV1BanksBankIdSharePostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof shareBankApiV1BanksBankIdSharePost>>, TError,{bankId: string;data: BankShareRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof shareBankApiV1BanksBankIdSharePost>>, TError,{bankId: string;data: BankShareRequest}, TContext> => {

const mutationKey = ['shareBankApiV1BanksBankIdSharePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof shareBankApiV1BanksBankIdSharePost>>, {bankId: string;data: BankShareRequest}> = (props) => {
          const {bankId,data} = props ?? {};

          return  shareBankApiV1BanksBankIdSharePost(bankId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ShareBankApiV1BanksBankIdSharePostMutationResult = NonNullable<Awaited<ReturnType<typeof shareBankApiV1BanksBankIdSharePost>>>
    export type ShareBankApiV1BanksBankIdSharePostMutationBody = BankShareRequest
    export type ShareBankApiV1BanksBankIdSharePostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Share bank with users
 */
export const useShareBankApiV1BanksBankIdSharePost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof shareBankApiV1BanksBankIdSharePost>>, TError,{bankId: string;data: BankShareRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof shareBankApiV1BanksBankIdSharePost>>,
        TError,
        {bankId: string;data: BankShareRequest},
        TContext
      > => {
      return useMutation(getShareBankApiV1BanksBankIdSharePostMutationOptions(options), queryClient);
    }
    /**
 * Remove users from bank share.

Only the owner can remove users.

Args:
    request (Request): Framework context.
    bank_id (UUID): The unique identifier of the bank.
    unshare_data (BankUnshareRequest): The list of users to remove.
    user_id (UUID): Authenticated user ID.
    service (BankService): Injected domain service.

Returns:
    APIResponse: Explicit success confirmation.
 * @summary Remove users from bank share
 */
export const unshareBankApiV1BanksBankIdUnsharePost = (
    bankId: string,
    bankUnshareRequest: BankUnshareRequest,
 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/banks/${bankId}/unshare`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bankUnshareRequest, signal
    },
      options);
    }



export const getUnshareBankApiV1BanksBankIdUnsharePostMutationOptions = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unshareBankApiV1BanksBankIdUnsharePost>>, TError,{bankId: string;data: BankUnshareRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof unshareBankApiV1BanksBankIdUnsharePost>>, TError,{bankId: string;data: BankUnshareRequest}, TContext> => {

const mutationKey = ['unshareBankApiV1BanksBankIdUnsharePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unshareBankApiV1BanksBankIdUnsharePost>>, {bankId: string;data: BankUnshareRequest}> = (props) => {
          const {bankId,data} = props ?? {};

          return  unshareBankApiV1BanksBankIdUnsharePost(bankId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UnshareBankApiV1BanksBankIdUnsharePostMutationResult = NonNullable<Awaited<ReturnType<typeof unshareBankApiV1BanksBankIdUnsharePost>>>
    export type UnshareBankApiV1BanksBankIdUnsharePostMutationBody = BankUnshareRequest
    export type UnshareBankApiV1BanksBankIdUnsharePostMutationError = ExceptionResponse | HTTPValidationError

    /**
 * @summary Remove users from bank share
 */
export const useUnshareBankApiV1BanksBankIdUnsharePost = <TError = ExceptionResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unshareBankApiV1BanksBankIdUnsharePost>>, TError,{bankId: string;data: BankUnshareRequest}, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unshareBankApiV1BanksBankIdUnsharePost>>,
        TError,
        {bankId: string;data: BankUnshareRequest},
        TContext
      > => {
      return useMutation(getUnshareBankApiV1BanksBankIdUnsharePostMutationOptions(options), queryClient);
    }
