/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ContestDetailResponse } from './contestDetailResponse';
import type { MetaResponse } from './metaResponse';
import type { PaginationResponse } from './paginationResponse';

export interface APIResponseContestDetailResponse {
  success?: boolean;
  status?: number;
  message?: string;
  data?: ContestDetailResponse | null;
  pagination?: PaginationResponse | null;
  meta: MetaResponse;
}
