/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for copying questions from one bank to another.

Carries the destination bank, the optional set of questions to copy, and a flag
that allows copying the full source bank when requested.
 */
export interface BankQuestionCopyRequest {
  /** Destination bank ID */
  target_bank_id: string;
  /** Optional list of question IDs to copy from the source bank */
  question_ids?: string[] | null;
  /** Copy all questions from the source bank when true */
  copy_all?: boolean;
}
