/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for standard bank responses.

Provides the standard view of a bank including metadata like IDs and timestamps.
 */
export interface BankResponse {
  /**
     * Bank name
     * @minLength 1
     * @maxLength 255
     */
  name: string;
  /** Bank description */
  description?: string | null;
  /** Bank ID */
  id: string;
  /** Creator user ID */
  created_by: string;
  /** Creation time */
  created_at: string;
  /** Last update time */
  updated_at: string;
}
