/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for bank creation requests.

Inherits all core fields from BankBase and requires them for initial creation.
 */
export interface BankCreate {
  /**
     * Bank name
     * @minLength 1
     * @maxLength 255
     */
  name: string;
  /** Bank description */
  description?: string | null;
}
