/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BankShareItem } from './bankShareItem';

/**
 * Schema for processing a bulk bank sharing request.

Contains a list of shares to add or modify for a bank.
 */
export interface BankShareRequest {
  /** List of users to share with */
  shares: BankShareItem[];
}
