/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ContestStatus } from './contestStatus';

/**
 * Schema for contest summary response (List view).
 */
export interface ContestSummaryResponse {
  /** Contest ID */
  id: string;
  /** Contest name */
  name: string;
  /** Contest description */
  description?: string | null;
  /** Contest image URL */
  image?: string | null;
  /** Contest start time (UTC) */
  start_time: string;
  /** Contest end time (UTC) */
  end_time: string;
  /** Contest status */
  status: ContestStatus;
  /** Contest creation time (UTC) */
  created_at: string;
  /** Whether contest is public */
  is_public: boolean;
}
