/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ScoringType } from './scoringType';

/**
 * Schema for creating a contest.
 */
export interface ContestCreate {
  /**
     * Contest name
     * @minLength 1
     * @maxLength 255
     */
  name: string;
  /** Contest description */
  description?: string | null;
  /** Contest image URL */
  image?: string | null;
  /** Whether contest is public */
  is_public?: boolean;
  /** Contest start time (UTC) */
  start_time: string;
  /** Contest end time (UTC) */
  end_time: string;
  /** Registration start time (UTC) */
  registration_start?: string | null;
  /** Registration end time (UTC) */
  registration_end?: string | null;
  /** Maximum number of teams allowed */
  max_teams?: number | null;
  /** Minimum team size */
  min_team_size?: number;
  /** Maximum team size */
  max_team_size?: number;
  /** Contest rules */
  rules?: string | null;
  /** Scoring type */
  scoring_type?: ScoringType;
}
