/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ContestStatus } from './contestStatus';

export type GetDeletedContestsApiV1ContestsDeletedGetParams = {
/**
 * Search by contest name
 */
search?: string | null;
/**
 * Filter by contest status
 */
contest_status?: ContestStatus | null;
/**
 * Page number (starts from 1)
 * @minimum 1
 */
page?: number;
/**
 * Number of contests per page
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};
