/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for managing instructors in a contest.
 */
export interface InstructorManageRequest {
  /** List of instructor IDs to assign or remove */
  instructor_ids: string[];
}
