/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionDifficulty } from './questionDifficulty';
import type { QuestionResponseTestcasesItem } from './questionResponseTestcasesItem';

export interface QuestionResponse {
  /** The problem statement and description */
  question_text: string;
  /** Difficulty level of the question */
  difficulty: QuestionDifficulty;
  /** List of allowed programming languages */
  allowed_languages: string[];
  /** List of testcases with input/output and visibility */
  testcases: QuestionResponseTestcasesItem[];
  /**
     * Time limit in milliseconds
     * @exclusiveMinimum 0
     */
  time_limit_ms: number;
  /**
     * Memory limit in megabytes
     * @exclusiveMinimum 0
     */
  memory_limit_mb: number;
  id: string;
  created_by: string;
  created_at: string;
  updated_at: string;
}
