/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionDifficulty } from './questionDifficulty';
import type { QuestionUpdateTestcases } from './questionUpdateTestcases';

export interface QuestionUpdate {
  question_text?: string | null;
  difficulty?: QuestionDifficulty | null;
  allowed_languages?: string[] | null;
  testcases?: QuestionUpdateTestcases;
  time_limit_ms?: number | null;
  memory_limit_mb?: number | null;
}
