/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Enumeration of scoring methods for contest evaluation.

Determines how submissions are evaluated and scored during contests,
affecting the judging workflow and result calculation.

Attributes:
    AUTO: Fully automatic scoring using predefined test cases and judges.
    MANUAL: Human-reviewed scoring for subjective or complex evaluation.
    HYBRID: Combined automatic and manual scoring for comprehensive assessment.
 */
export type ScoringType = typeof ScoringType[keyof typeof ScoringType];


export const ScoringType = {
  AUTO: 'AUTO',
  MANUAL: 'MANUAL',
  HYBRID: 'HYBRID',
} as const;
