/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Amrita ICPC Coding Platform - Backend
 * A backend tool for Amrita ICPC Coding Platform
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  APIResponse,
  ExceptionResponse,
  UserProfile,
  UserSyncResponse
} from '../../model';

import { axiosWithAuth } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Users
 */
export const getUsersApiV1UsersGet = (

 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/users/`, method: 'GET', signal
    },
      options);
    }




export const getGetUsersApiV1UsersGetQueryKey = () => {
    return [
    `/api/v1/users/`
    ] as const;
    }


export const getGetUsersApiV1UsersGetQueryOptions = <TData = Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError = ExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersApiV1UsersGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersApiV1UsersGet>>> = ({ signal }) => getUsersApiV1UsersGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersApiV1UsersGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersApiV1UsersGet>>>
export type GetUsersApiV1UsersGetQueryError = ExceptionResponse


export function useGetUsersApiV1UsersGet<TData = Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError = ExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersApiV1UsersGet>>,
          TError,
          Awaited<ReturnType<typeof getUsersApiV1UsersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersApiV1UsersGet<TData = Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError = ExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersApiV1UsersGet>>,
          TError,
          Awaited<ReturnType<typeof getUsersApiV1UsersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersApiV1UsersGet<TData = Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError = ExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Users
 */

export function useGetUsersApiV1UsersGet<TData = Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError = ExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersApiV1UsersGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersApiV1UsersGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create User
 */
export const createUserApiV1UsersPost = (

 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<APIResponse>(
      {url: `/api/v1/users/`, method: 'POST', signal
    },
      options);
    }



export const getCreateUserApiV1UsersPostMutationOptions = <TError = ExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserApiV1UsersPost>>, TError,void, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof createUserApiV1UsersPost>>, TError,void, TContext> => {

const mutationKey = ['createUserApiV1UsersPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUserApiV1UsersPost>>, void> = () => {


          return  createUserApiV1UsersPost(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUserApiV1UsersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createUserApiV1UsersPost>>>

    export type CreateUserApiV1UsersPostMutationError = ExceptionResponse

    /**
 * @summary Create User
 */
export const useCreateUserApiV1UsersPost = <TError = ExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserApiV1UsersPost>>, TError,void, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUserApiV1UsersPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCreateUserApiV1UsersPostMutationOptions(options), queryClient);
    }
    /**
 * Get current logged-in user details from JWT.
 * @summary Get Me
 */
export const getMeApiV1UsersMeGet = (

 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<UserProfile>(
      {url: `/api/v1/users/me`, method: 'GET', signal
    },
      options);
    }




export const getGetMeApiV1UsersMeGetQueryKey = () => {
    return [
    `/api/v1/users/me`
    ] as const;
    }


export const getGetMeApiV1UsersMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError = ExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiV1UsersMeGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>> = ({ signal }) => getMeApiV1UsersMeGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeApiV1UsersMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>>
export type GetMeApiV1UsersMeGetQueryError = ExceptionResponse


export function useGetMeApiV1UsersMeGet<TData = Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError = ExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiV1UsersMeGet<TData = Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError = ExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiV1UsersMeGet<TData = Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError = ExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiV1UsersMeGet<TData = Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError = ExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1UsersMeGet>>, TError, TData>>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeApiV1UsersMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Synchronize Keycloak users with the local database.

Only administrators can trigger this operation. This endpoint fetches all users
from Keycloak, retrieves their group assignments, and creates new user records
in the database if they don't already exist.

Args:
    admin_user: Current authenticated admin user
    db: Database session

Returns:
    Response with sync status and number of users synced

Raises:
    PermissionDeniedError: If user is not an admin
    KeycloakSyncError: If sync operation fails
 * @summary Sync Keycloak Users
 */
export const syncKeycloakUsersApiV1UsersSyncKeycloakUsersPost = (

 options?: SecondParameter<typeof axiosWithAuth>,signal?: AbortSignal
) => {


      return axiosWithAuth<UserSyncResponse>(
      {url: `/api/v1/users/sync-keycloak-users`, method: 'POST', signal
    },
      options);
    }



export const getSyncKeycloakUsersApiV1UsersSyncKeycloakUsersPostMutationOptions = <TError = ExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncKeycloakUsersApiV1UsersSyncKeycloakUsersPost>>, TError,void, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
): UseMutationOptions<Awaited<ReturnType<typeof syncKeycloakUsersApiV1UsersSyncKeycloakUsersPost>>, TError,void, TContext> => {

const mutationKey = ['syncKeycloakUsersApiV1UsersSyncKeycloakUsersPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncKeycloakUsersApiV1UsersSyncKeycloakUsersPost>>, void> = () => {


          return  syncKeycloakUsersApiV1UsersSyncKeycloakUsersPost(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncKeycloakUsersApiV1UsersSyncKeycloakUsersPostMutationResult = NonNullable<Awaited<ReturnType<typeof syncKeycloakUsersApiV1UsersSyncKeycloakUsersPost>>>

    export type SyncKeycloakUsersApiV1UsersSyncKeycloakUsersPostMutationError = ExceptionResponse

    /**
 * @summary Sync Keycloak Users
 */
export const useSyncKeycloakUsersApiV1UsersSyncKeycloakUsersPost = <TError = ExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncKeycloakUsersApiV1UsersSyncKeycloakUsersPost>>, TError,void, TContext>, request?: SecondParameter<typeof axiosWithAuth>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncKeycloakUsersApiV1UsersSyncKeycloakUsersPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSyncKeycloakUsersApiV1UsersSyncKeycloakUsersPostMutationOptions(options), queryClient);
    }
